es-core/src/AudioManager.cpp
A quick fix for Segmentation fault when ES stopping: 
release the Mix_HookMusicFinished callback when the AudioManager deinit, otherwise it will access a null callback.
=> Fix Segmentation fault when stopping

es-app/src/guis/GuiMenu.cpp
**RetroArch 1.6.3**
Achievements Verbose Mode'. Ability to display cheevos related messages in OSD, useful for RetroAchievements users.
**RetroArch 1.6.8**
Add support for RetroAchievements Leaderboards.
**RetroArch 1.7.2**
Add option to automatically take a screenshot when an achievement is triggered.
=> retroachievements: leaderboards, verbose and screenshot

es-core/src/guis/GuiInputConfig.cpp
*This fixed the bug when toggling the visibility by calling `setOpacity` on the TextComponent
didn't have any effect.
Credits : @cmitu
Commit : 3ea6a7423b9f7b71bff50425d1bbad55eeb140df
=> Fix the `opacity` for the hold-to-skip message

es-app/src/views/SystemView.cpp
Credit: https://github.com/bullghost/batocera-emulationstation/commit/95847321cdc70a447a2cb58fa0f29e6a763b8675
=> remove double render infobar

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h
This relies on a Bash script located in /recalbox/scripts/batocera-retroachievements-info
which retrieved the webpage from https://retroachievements.org and parses it
to produce a 1-line summary of the current score and standings.
PR for the Bash script will be following this one.
=> Added a menu for RetroAchievements score and standings

es-app/src/scrapers/ScreenScraper.h
ScreensScraper.fr has changed the SSL certificate, they now use a wildcard (*.screenscraper.fr) certificate.
This makes the screenscraper.fr hostname no longer available, so let's switch to www. for the API url. The change happened sometime around 20 April, but it doesn't seem to affect a lot of users.Apparently other scrapers haven't been using the non-www API endpoint.
Credit: Cristi Mitrana
Commit: 6e123ba8c60897a6f7e9dff8cb1f606576ab859c
Source: https://github.com/RetroPie/EmulationStation/pull/561/commits/6e123ba8c60897a6f7e9dff8cb1f606576ab859c
=> Scraper: change ScreenScraper API URL

es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiScreensaverOptions.cpp
- "Random video" will play all the videos that have been scraped. When you fancy play the game that is showing up, press "start". Several options, like adding the name of the game and the console as an overlay over the video. 
- "Slideshow" will take the images that were scraped and display them as a screensaver.
- Added two sub-menus in "UI Settings" to configure the options for those two screensavers.
=> Screensavers: added "random video" (aka demo mode) and "slideshow"

es-app/src/FileData.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-core/src/AudioManager.cpp, es-core/src/AudioManager.h
Enable system-specific background music (`audio.persystem=1` in `batocera.conf`) in order to play only the .mp3 and .ogg files that are in `/userdata/music/` and `/userdata/music/system_that_is_currently_on`.
For example, if you have two folders `/userdata/music/nes` and `/userdata/music/psx`, only the `nes` musics will be played when you are in the NES system in ES, while only the `psx` musics will be played when you are in PlayStation. Musics in the top folder `/userdata/music/` will be played anywhere.
There is also a new GUI option in "Sound settings" to set this up.
=> Add an option for per-system background music

es-app/src/scrapers/Scraper.cpp
*This minor change fixes the Scrape issue for users who let TheGameDB default. ScreenScraper is much more perfomant than TheGamesDB
=> Default Scrape source replaced by ScreenScraper

es-app/CMakeLists.txt, es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiBezelInstall.cpp, es-app/src/guis/GuiBezelInstall.h, es-app/src/guis/GuiBezelInstallStart.cpp, es-app/src/guis/GuiBezelInstallStart.h, es-app/src/guis/GuiMenu.cpp
New menu in EmulationStation (`System Settings` / `Updates`, next to the themes manager as it's very similar in its concept) to install/remove theBezelProject for each system installed on Batocera. Obviously, it requires the `batocera-es-thebezelproject` menu and changes in the libretro configgen that have been PRed earlier.
Once installed, it can be enabled in the `decorations` menu, as other decorations.
=> Integration with theBezelProject

es-core/src/AudioManager.cpp, es-core/src/AudioManager.h
- SDL_CloseAudio() was called... Instead of Mix_CloseAudio()
- Fix Mix_HaltMusic() / Mix_FreeMusic(currentMusic) calling order otherwise FreeMusic could hang and not respond anymore.
- Don't call Mix_FadeOutMusic when playing a new music (ex: per system music) because it lags too much.
=> Fix Music not playing when returning from a game

es-core/src/Settings.cpp
On a TV with a Raspberry Pi, ES looks like it is flickering.
Set to true by default on every system.
=> Set VSync on by default on Raspberry Pi

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiMenu.cpp, es-app/src/main.cpp, es-core/CMakeLists.txt, es-core/src/Settings.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/ThreadPool.cpp, es-core/src/utils/ThreadPool.h
- Load systems using threaded loading when processor threads > 2 (so it doesn't apply on pi0), making loading systems faster.
- Added a progressbar during loading (red for batocera)
- The titlescreen/progressbar is also displayed when "UPDATE GAMES LISTS" runs.
- Moved updateGamelist() call in deleteAllSystems : it was previously called by  ~SystemData and was also called when a system was loaded but deleted because it had no roms in it.
=> Threaded loading of systems + added a progressbar during loading.

es-app/src/components/ScraperSearchComponent.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/main.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/PowerSaver.cpp, es-core/src/PowerSaver.h, es-core/src/Settings.cpp, es-core/src/SystemConf.cpp, es-core/src/components/BusyComponent.cpp, es-core/src/components/IList.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoVlcComponent.cpp, es-core/src/components/VideoVlcComponent.h, es-core/src/guis/GuiInfoPopup.cpp, es-core/src/guis/GuiInfoPopup.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/resources/TextureData.cpp, es-core/src/resources/TextureData.h, es-core/src/resources/TextureResource.cpp, es-core/src/resources/TextureResource.h
- VLC Video : Stop coping bytes in memory. Stop deleting / creating texture for each frame -> Just update the texture. ( should be really really faster ! )
- VLC Video : Don't copy bytes / delete / create texture when VLC has no new rendered frame !!!!
- VLC Video : Release the texture if it is not visible anymore ( when moving to another gamelist ) -> Retropie's component keep the last frame texture in memory permanently !!!!
- VLC Video : Added developer option "OPTIMIZE VIDEO VRAM USE" for VLC : if a video is bigger than the display, ask VLC to size it.
- VLC Video : Support for extra command line arguments in bacotera.conf file, variable vlc.commandline=xxx ( intended for debugging )
- OMX Player : Fixed omxplayer executable path.
- VideoComponent : Disabled async for static images. …
=> Video components : lot of fixes !!

es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h, es-core/src/renderers/Renderer.cpp, es-core/src/resources/TextureDataManager.cpp, es-core/src/resources/TextureDataManager.h
- TextComponent : reviewed glow code ( avoid using lambas ) - potential fix for rpi crash.
- TextureDataManager : Better threading, no more sleeping 10 ms to process the queue.
- Collection settings : fixed some settings were not saved.
- Screenscraper : Added "title screenshot" as source.
- ThemeData : Changed the way to collect subset to avoir reparsing the xml files + fixed tinyScreen & ifHelpPrompts attributes on view elements
=> Potential fix for rpi crash & misc optimisations

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/FileFilterIndex.cpp, es-app/src/FileFilterIndex.h, es-app/src/guis/GuiGamelistFilter.cpp, es-app/src/guis/GuiGamelistFilter.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiGamelistOptions.h, es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/Settings.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/MenuComponent.cpp, es-core/src/components/MenuComponent.h, es-core/src/components/TextEditComponent.cpp, es-core/src/components/TextEditComponent.h, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoVlcComponent.cpp, es-core/src/components/VideoVlcComponent.h, es-core/src/guis/GuiTextEditPopup.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.h, es-core/src/utils/StringUtil.cpp, resources/search.svg
- Filter : Add text search filter in gamelist options 
- StringUtil.toUpper/toLower -> Has problems with accents
- Settings : Changed default collections to "all,favorites" instead of "2players,4players,favorites,recent" ( "all games" list will be really useful combined to text search )
- Vlc Component : fix Gridview don't pass size for OptimizeVideo setting
- OMX VideoPlayerComponent : fix Position/Size should be rounded instead of Truncated.
- GridView / Other views : add use of l2 / r2 to navigate in systems. 
- SystemView : use pagedown/pageup to scroll 10 systems
=>  Filter : Add text search filter in gamelist options + misc fixes

CMakeLists.txt
With that, an automated build for Windows is now available at : 
https://github.com/fabricecaruso/batocera-emulationstation/releases
=> Windows automated build : disable boost for msvc

es-app/src/guis/GuiBezelInstallStart.cpp
The last feature on bezels (install bezels through a download queue) had a wrong copy/paste from the theme install code with a bezel seen as `CONTENT_THEME` (and not `CONTENT_BEZEL` see https://github.com/batocera-linux/batocera-emulationstation/commit/922ff532f9150d11705b486fd18167e8616be274#r35337420). That means the script for downloading the theme with a bezel name was failing - and a misleading error was presented to the user (theme not found).
=> Fixed a bug preventing bezels install.

es-app/src/CollectionSystemManager.cpp, es-app/src/FileFilterIndex.cpp, es-app/src/FileFilterIndex.h, es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h, es-core/src/ThemeData.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageGridComponent.h, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h, es-core/src/guis/GuiTextEditPopupKeyboard.cpp, es-core/src/resources/Font.cpp, es-core/src/resources/Font.h
- GridView : Support for marquee using <image name="gridtile.marquee">element.
- GridView : fixed <text name="gridtile"> positionning. <pos> element is now supported (but optionnal).
- GuiTextEditPopupKeyboard : Y button does not work to run Shift switch
- TextComponent : Support for reflexion
- Screenscraper : take wheel as preference when marquee is ON 
- Screenscraper : check invalid responses when downloading medias 
- Collection edition : Display editing collection name in notifications.
- Screenscraper : TITLE SCREENSHOT was duplicated in image choice.
- Scraper : Thumbnail preview don't work anymore ( related to httpreq recent changes )
=>  GridView : Support for marquee using + misc things

es-app/src/FileData.cpp, es-app/src/guis/GuiGameScraper.cpp, es-app/src/guis/GuiMetaDataEd.cpp, es-app/src/guis/GuiUpdate.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/scrapers/ScreenScraper.h, es-app/src/views/SystemView.cpp, es-core/src/AudioManager.cpp
- ScreenScraper : Use "jeuRecherche" instead of jeuInfos when using manual Metadata/Scrape function -> "jeuRecherche" can return multiple results.
- GuiGameScraper : Fixed size on small screens (GPI)
- Update : REBOOT SYSTEM TO APPLY message was not localisable 
- SystemView : moving -10/+10 in system list creates big lags -> Move directly to system without animating.
- AudioManager : don't try to load IDV3 if file ext is not mp3 & avoid trying idv3 reading on ogg or wav files ( Darknior crashes ? )
- Game launch : fixed %EMULATOR% & %CORE% command line variables ( usable on WIN32 version )
=> Misc fixes

es-app/src/ApiSystem.cpp, es-app/src/FileData.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiGeneralScreensaverOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSlideshowScreensaverOptions.cpp, es-app/src/views/SystemView.cpp, es-core/src/Settings.cpp, es-core/src/ThemeData.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/ImageGridComponent.h
- Restored screensaver old submenu system ( more readable ) + allow "start" to run games.
- Fix onShow not called when returning back from games & kodi & game runned from screensaver -> Display can be black, or back flickering when changing system.
- GridView : Add sound support imagegrid.scrollSound
=> ScreenSaver : Display game text / system + fading transition

es-app/src/guis/GuiGameScraper.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMetaDataEd.cpp, es-app/src/guis/GuiScraperMulti.cpp, es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-core/src/LocaleES.cpp, es-core/src/Settings.h, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/AsyncNotificationComponent.cpp, es-core/src/components/BusyComponent.cpp, es-core/src/components/MenuComponent.cpp, es-core/src/components/NinePatchComponent.cpp, es-core/src/guis/GuiDetectDevice.cpp, es-core/src/guis/GuiInfoPopup.cpp, es-core/src/guis/GuiInputConfig.cpp, es-core/src/guis/GuiMsgBox.cpp, es-core/src/guis/GuiTextEditPopup.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.cpp, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp, resources/off.svg, resources/on.svg
- Renderer : upscaled image are blurred (not usable in themes like es_pixel) since Retropie's Tomaz Renderer refactoring.
- Video ScreenSaver options : OMX still visible on every platform 
- Theming : Support for "lang" attribute ( manage multiple languages in a theme )
- Themes : Support for user defined subsets.
- Themes : Support for "shaders"
- Themes : Menu background -> Support for custom corner size ( usefull for menu with shadows )
PS : Don't forget to bump my es_carbon theme to see new things....
=>  Renderer blur fix & support for multiple languages in Theming 

es-app/src/SystemData.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/scrapers/ScreenScraper.h, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/HelpStyle.cpp, es-core/src/HelpStyle.h, es-core/src/HttpReq.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h, es-core/src/components/VideoVlcComponent.cpp, es-core/src/components/VideoVlcComponent.h
- Theming Add <view name="screen" > to manage fixed components that are to be "statically" displayed ( crt or scanlines effects, clock )
- Clock : Complete rewrite using a text component - Now customisable in <view name="screen" > <text ="clock">
- Vlc Video : RPI only :  A lot of videos are encoded in 60fps on screenscraper. Add a limit at 30fps for transfers to opengl textures to save CPU.
- Video component : Add element <snapshotSource> (image, thumbnail, marquee) to define the image snapshot source.
- Screenscraper : Temp Fix. We sometimes receive #screenscraperserveur# in the url instead of the server.
=> Theming Added <view name="screen" > to manage fixed components.

es-app/CMakeLists.txt, es-app/src/PlatformId.cpp, es-app/src/PlatformId.h, es-app/src/guis/GuiScraperStart.cpp, es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/GamesDBJSONScraper.h, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/scrapers/ScreenScraper.h, es-app/src/scrapers/md5.cpp, es-app/src/scrapers/md5.h, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h, es-core/src/resources/TextureData.cpp, es-core/src/utils/FileSystemUtil.cpp
supergrafx, amigacd32, amigacdtv, atomiswave, cavestory, gx4000, lutro, moonlight, naomi, neogeocd, pcfx, pokemini, prboom, satellaview, sufami, zx81, gb2players, gbc2players, 3ds, sg1000, odyssey2, oricatmos, windows, vpinball, fpinball, o2em, channelf, oric, thomson, samcoupe, OpenBOR, uzebox, apple2gs, Spectravideo, palm, daphne.
+ Screenscraper : Use md5 checksum in screenscraper requests 
+ Screenscraper : Handle "maximum threads per minute" error with delayed retry.
+ Scrapers : Optimize scraper incremental mode.
+ Fix SVG proportions
=> Scraper : Add missing & fix existing systems

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h
Used to avoid conflicts between same rom name in different system + avoid problems reading batocera.conf when = or # caracters are found.
See FileData::getConfigurationName() for new naming rules which are :
systemname.filename (without spaces without = without #)
This PR is to merge only when script are to be adapted.
=> Game specific configuration : change naming convention

es-app/src/components/RatingComponent.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/SystemView.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ImageComponent.cpp
Fix : Theme subset selection can be empty & lead to a crash
Fix : VERTICAL_WHEEL carousel logo position on some themes using rotation by logo size + ensure loading order for themes <= 4
Fix : Rating Component drawing on some themes.
Fix : ImageComponent clipping with rotation
=> Theming Fixes

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/FileSorts.cpp, es-app/src/FileSorts.h, es-app/src/SystemData.cpp, es-app/src/guis/GuiFastSelect.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/Settings.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h
- Added ".." item when navigating in a subfolder.
- Faster case insentisive sorting + refactored sort calls.
- Show labels on grid items using default folder/game image, when labels are not defined by the theme.
- Added option "SHOW FILENAMES IN LISTS" to display filenames instead of scrapped names ( except arcade systems using mamenames )
=> Fixes : Folder navigation & sortings

es-app/src/guis/GuiMenu.cpp
This is the ES configuration screen for https://github.com/batocera-linux/batocera.linux/pull/1024   
It basically manages the three new fields that have been added in `batocera.conf`:
```
global.ai_service_enabled=1  # Is the service enabled?
global.ai_service_url=       # URL of the translation service to use
global.ai_target_lang=Fr     # Language to translate into (2-char language code)
```
=> LibRetro AI service for game translation.

es-app/src/guis/GuiMenu.cpp
Just because it makes a lot more sense for many new users. "Why are bezels and themes in Updates?" - putting "downloads" in the same menu title will probably help a lot.
=> Renamed "Updates" menu (because themes+bezels)

es-app/src/guis/GuiMenu.cpp, locale/emulationstation2.pot, locale/lang/es/LC_MESSAGES/emulationstation2.po
This will let you add up to 6 frames of run-ahead globally, per system, or per game, batocera.conf needs to be updated to handle 
* global.runahead
* global.secondinstance
* [system].runahead
* [system].secondinstance
* [game].runahead
* [game].secondinstance
=> Add run-ahead options

es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp
=> OpenGLES : Use glDrawArrays GL_TRIANGLE_FAN instead of unsupported glVertex2f

es-core/src/ThemeData.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h
true -> always center the selection
partial -> center the selection except if at begin or end of gamelist ( was the previous default for false )
false -> never center selection
Default becomes "false" in vertical layout. ( instead of partial )
Default is "partial" in horizontal layout.
+ TextComponent : fix multiline calculation
=> GridView.centerSelection : add "partial" value & changed false value behaviour

es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h
- Created "subset" element to group includes & avoid repetitions of subset attributes in includes.
- Gamelist customisation per system is done using attribute appliesTo="viewname". 
```
<subset name="option" appliesTo="grid">
<include name="yes">./samplefile0.xml</include>
<include name="no">./samplefile1.xml</include>
</subset>
```
=> Allow gamelist subsets storage/customisations per system 

es-app/src/FileData.cpp, es-app/src/SystemData.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp
- Presence of game and also its folder when the game is in a subfolder.
- fix detection of single game in folder using option "show folders / having multiple games"
- fix crash when navigating to parent folder after "show folder" option change
- Fix gamelist filters not working anymore
=> Fix : Grouped systems subfolder management.

es-app/src/FileData.cpp, es-app/src/MetaData.cpp, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/DetailedGameListView.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/VideoGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.h, es-core/src/utils/TimeUtil.cpp, es-core/src/utils/TimeUtil.h
Added a new `<gametime>` XML attribute in `gamelist.xml` that keeps track of how long you've played a game. It displays the total number of seconds the game has been launched from ES. This new attribute needs to be displayed by the themes (I'd recommend to add it to Batocera default theme).
To avoid false positives, it's logged only if the calculated game time for a session is >10 seconds.
Structure of the new attribute in gamelist.xml:
```
<gameList>
<game>
....
<gametime>1245</gametime>
</game>
</gameList>
```
=> gamelist.xml: added <gametime> (playing time)

es-app/src/FileFilterIndex.cpp, es-app/src/guis/GuiGamelistFilter.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/views/SystemView.cpp, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/Window.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h, es-core/src/resources/TextureData.cpp, es-core/src/resources/TextureData.h, es-core/src/resources/TextureDataManager.cpp, es-core/src/resources/TextureDataManager.h, es-core/src/resources/TextureResource.cpp, es-core/src/resources/TextureResource.h
- Allow Themes to declare image smoothing for (background) images when they are upscaled.
+ Translation : Somes menu options are not ready for translation 
+ SystemView : Support extra="static" items -> static items don't scroll with systems & are in a fixed position.
=> ImageComponent : Add boolean 'image.linearSmooth' + SystemView : Support extra="static" items

es-app/src/main.cpp, es-core/src/ImageIO.cpp, es-core/src/ImageIO.h, es-core/src/components/ImageGridComponent.h, es-core/src/resources/TextureData.cpp, es-core/src/resources/TextureData.h, es-core/src/resources/TextureDataManager.cpp, es-core/src/utils/FileSystemUtil.cpp
Improves performance & reduce lags when async loading images (ie. in grid view) with slow access time drives (mecanical HDDs/NAS/Slow SD card) using file "/userdata/system/configs/emulationstation/imagecache.db".
=> ImageCache : Reduce lags for image async loadings

es-app/src/main.cpp, es-core/src/PowerSaver.cpp, es-core/src/VolumeControl.cpp, es-core/src/components/ButtonComponent.cpp, es-core/src/components/ButtonComponent.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/VolumeInfoComponent.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.cpp, es-core/src/resources/Font.cpp
- Volume control should work now when Volume changed by external code.
- Better font sizing for small screen ( depend on resolution )
- Removed button borders on virtual keyboard for more readability
- Powersaver : Run main loop at least once per second ( required if a component like volume control or video has to suspend the powersaver )
- ImageComponent : small fix for old theme using 0 width images ( old minSize mode  - ie : Simple theme )
=> SmallScreens ( goa, gpi ) Fixes

es-app/src/views/gamelist/ISimpleGameListView.cpp
Avoid accidental game launches if transition is still running if the user accidentally "double clicked" on the system view.
=> Fix : Avoid accidental game launches

es-app/src/guis/GuiMenu.cpp
RetroArch used to always pause after AI translation, now it's controlled by a specific setting in `retroarch.cfg` (by default: unpaused).
Corresponding PR in batocera.linux: https://github.com/batocera-linux/batocera.linux/pull/1205
=> Added an option to pause after screen translation

es-app/src/FileData.cpp
I left it for the Windows build, not sure if it's also still needed there (@fabricecaruso?).
=> fixed '--hash' option (depcreated for Linux?)

es-app/src/Gamelist.cpp
When the gamelist had external changes, recovery files are never deleted.
=> Fix : Gamelist recovery not cleaned up if recovery file are obsolete

es-app/src/guis/GuiMenu.cpp
and indexing hashes -> It can lead to a crash because some options need to delete all systems / rebuild all gamelist.
=> CrashFix : prevent user from going in collections menu while scrapping

es-app/src/guis/GuiGamelistOptions.cpp
Deletion of a game in a group does not work & can lead to a crash.
=> Fix : Editing metadatas for a game in a group is not working. 

es-core/src/components/BatteryIndicatorComponent.cpp
/sys/class/power_supply/battery/status contains an extra \n char
=> Fix Battery indicator for GOA.

es-app/src/SystemScreenSaver.cpp, es-app/src/guis/GuiInstallStart.cpp, es-app/src/guis/GuiInstallStart.h, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp
- even if defined different in the theme.
- Fix : INSTALL ON NEW DISK screen may crash if all options are not set
- Fix : Screensaver decoration viewport calculation when screen proportion is different than the bezel proportion (4:3 screens)
=> Fix : The gamelist logo is always the same as the systemview 

es-app/src/ApiSystem.h, es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-app/src/Win32ApiSystem.cpp, es-app/src/Win32ApiSystem.h, es-app/src/components/TextListComponent.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiNetPlay.cpp, es-app/src/guis/GuiNetPlay.h, es-app/src/main.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/Splash.cpp, es-core/src/SystemConf.cpp, es-core/src/renderers/Renderer.cpp
- SystemConf : Don't serialise default values & auto or empty values to avoid file growing.
- es_features : System management
- Netplay : Force the appropriate core when running a game to join a server.
- Netplay : Better management using es_features
- Netplay : UI Fixes - don't allow netplay server if current core does not support it.
- Random game : Fixes.
- Advanced options : Fixes
- Splash : Enable linearSmooth flag in background image.
- Menu UI : Fix infinite scroll with pageup/pagedown.
- Windows : getVideoModes without external script
- Windows : Transmit monitorId to emulatorLauncher
- Windows : fix --video command line.
- Windows : fix window restore after game exit with --fullscreen active.
=> Lot of fixes & things

es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/SystemView.cpp, es-core/src/resources/TextureDataManager.cpp, es-core/src/resources/TextureResource.cpp, es-core/src/utils/FileSystemUtil.cpp, locale/lang/es/LC_MESSAGES/emulationstation2.po, locale/lang/es_MX/LC_MESSAGES/emulationstation2.po, locale/lang/fr/LC_MESSAGES/emulationstation2.po, locale/lang/it/LC_MESSAGES/emulationstation2.po, locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po, locale/lang/pt_PT/LC_MESSAGES/emulationstation2.po
- Replace "N GAMES AVAILABLE" with "N ITEMS" for systems with platform.ignore ( screenshots ) & removed the word "AVAILABLE"
- Fix TextureResource maxsize management 
- Windows : Fix bezel installer
=>  Fix TextureResource & Replace "N GAMES AVAILABLE"

CMakeLists.txt
Add an option to force BCM (=rpi)
the option RPI is not set by batocera and seems to be only for the omx player. but i understand that even without this option set, the omx is enabled.
without this option, we get linker errors (i don't know why it didnt occured before)
=> bcm option

es-core/src/AudioManager.cpp
Background music: added support for .flac, .wav and popular .mod chiptune formats (.mod, .xm., .stm, .s3m, .far, .it, .mtm, .669...)
(Fixed previous crappy PR)
=> Added additional formats for background music

es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp, es-core/src/InputManager.cpp, es-core/src/guis/GuiInputConfig.cpp
- Disable approximations based on name -> XInput compatible controllers can have the same name, but differents Guids.
=> Windows only : Controllers Guids have to be exact

es-app/src/Gamelist.cpp, es-app/src/views/ViewController.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h
++ Windows only : createRelativePath not always working relative to %HOME%, making custom collections using non relative paths.
=>  Fix : Selection returning to root folder after launching a game from a subfolder

es-core/src/InputManager.cpp, es-core/src/ThemeData.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/NinePatchComponent.cpp, es-core/src/guis/GuiInputConfig.cpp
+ White background when custom backgroundImage was defined and backgroundCornerSize was set at 0 on tiles 
+ clipping issue on Retropie gridviews using autolayout.
=> Fix : GridView compatibility with retropie was broken with some themes.

es-app/src/guis/GuiSettings.cpp, es-app/src/guis/GuiSettings.h, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-core/src/GuiComponent.cpp, es-core/src/components/MenuComponent.cpp
Using B button...
Note/Todo : Systems with "manufacturer: Misc. Arcade" and "manufacturer: Misc. Port" in es_systems.yml should be renamed to "Arcade" & "Ports" -> Using the word "Misc." is really ugly & makes the sort order not undestandable.
=> SystemView Manufacturer bar ( when systems are sorted by manufacturers )

es-app/src/guis/GuiRetroAchievements.cpp
Only the very bottom of a `TitleIcon` is displayed, and it feels like wasted real estate on small screens like OGA
=> Removed RetroAchievement avatar on small screens

es-app/src/FileFilterIndex.h, es-app/src/Gamelist.h, es-app/src/MetaData.h, es-core/src/Settings.h, es-core/src/Sound.h
Compiles both with GCC 9.3 and GCC 10.1
=> Fix gcc10 compilation (C++ std::string missing header)

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMetaDataEd.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/BasicGameListView.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/IGameListView.h, es-core/src/ImageIO.cpp, es-core/src/Window.cpp
- Add manual icon + Renamed "QUIT" (select) menu to QUICK ACCESS.
- Defer gamelist animation to make sure they always play. (Sometimes they did not due to loading time) 
- Refactored Game Deletion + Deleting a game now removes the associated medias.
- Some Performance improvements for collections.
- Fix SHOW SYSTEM NAME IN COLLECTIONS switch
- Fix imagecache saving pdftmp & tmp files metadatas.
=> Misc fixes & enhancements

es-app/src/ApiSystem.cpp, es-app/src/SystemData.cpp, es-app/src/Win32ApiSystem.cpp, es-app/src/Win32ApiSystem.h, es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-core/src/GuiComponent.cpp, es-core/src/components/BatteryIndicatorComponent.cpp, es-core/src/components/ButtonComponent.cpp, es-core/src/components/ButtonComponent.h, es-core/src/components/ComponentGrid.cpp, es-core/src/components/ControllerActivityComponent.cpp, es-core/src/components/ControllerActivityComponent.h, es-core/src/components/TextEditComponent.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.h
- Add Quick search on systemView
- Fix battery indicator alignement
- GridComponent (menus&osk) : fix navigation through spanned cells
- SystemData : restored old Retropie search for gamelists in .emulationstation/gamelists folder, when default gamelist is not found.
- Windows Only : Add batocera-ports to updater when in beta channel.
=> Redesigned OnScreen Keyboard + Quick search on systemView

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/SystemData.cpp, es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiBatoceraStore.cpp, es-app/src/guis/GuiBatoceraStore.h, es-app/src/guis/GuiBezelInstallStart.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-core/src/Settings.cpp, es-core/src/components/ControllerActivityComponent.cpp, es-core/src/components/ControllerActivityComponent.h, es-core/src/platform.cpp
- Content Downloader : Refresh Xml when content installed or removed.
- Battery indicator : Fix option missing after being disabled.
- Battery indicator : Fix text superposition.
- Win32 : Add padtokey paths resolutions relative to emulatorLauncherPath.
- p2k compatibility : stop converting when scrapping -> Convert only on demand
=> Startup System : Add option "RESTORE LAST SELECTED" + Fixes

es-app/src/guis/GuiImageViewer.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h
This will add a themable cheevos icon (similar to the favorite star) for games that have cheevos, used in conjunction with the cheevos scan.
I tried this on my branch (EmuELEC), I have not tried it on the Batocera ES directly, before merging someone should test this first just to make sure nothing else breaks in Batocera. 
A (very bad) example image using:
```
<image name="gridtile.cheevos">
<path>./assets/trophy.svg</path>
<pos>0.0 0.4</pos>
<maxSize>0.15 0.15</maxSize>
<origin>0 1</origin>
<color>282828</color>
</image>
<image name="gridtile.cheevos:selected">
<path>./assets/trophy.svg</path>
<color>${cgtbgedgeselect}</color>
</image>
```
=> Themable gridtile.cheevos for Retroachievements 

es-core/src/renderers/Renderer.cpp
In order to make the OGS layout as "small screen" (otherwise fonts are too small to be read).
It might have a side effect for those using 640x480 resolution -- but actually the "small screen" layout might be better for them as well. Let's see what their feedback is.
=> Fix for OGS (small screen)

CMake/Packages/FindOpenGLES2.cmake
pkg-config may provide additional link flags, such as `-lmali` in the newer libmali versions.
Fixes #741
=> FindOpenGLES2: Use pkg-config

es-app/src/scrapers/GamesDBJSONScraper.cpp
The new values are from https://api.thegamesdb.net/ Swagger UI.
Got when calling /v1/Platforms and /v1/Games/ByGameName for some Daphne games.
=> TheGamesDB: Update ID for Amiga CD32 and Daphne

es-app/src/ApiSystem.cpp, es-app/src/Gamelist.cpp, es-app/src/RetroAchievements.cpp, es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiImageViewer.cpp, es-app/src/guis/GuiKeyboardLayout.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/ArcadeDBJSONScraper.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h, es-app/src/views/gamelist/DetailedContainer.cpp, es-app/src/views/gamelist/DetailedContainer.h, es-core/src/GuiComponent.cpp, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h, es-core/src/ImageIO.cpp, es-core/src/Log.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h, es-core/src/utils/StringUtil.cpp, es-core/src/utils/ZipFile.cpp, locale/lang/fr/LC_MESSAGES/emulationstation2.po
"unzipFile" is using 7zr for zip files, but it fails, so hashes are wrong because _**7z can't read zip files since batocera 29**_.
-> Use internal zip library instead
=> Retroachievements : Fix hashes calculation for some zip files

es-app/src/FileData.cpp, es-app/src/SystemData.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/SystemConf.cpp
+ Fix : Potential 'Black' gamelist after adding a game to favorites or returning from a game.
+ Fix crash when the same file is referenced in multiple m3u files
+ Save snapshots : global.autoSave -> set default to 2 (SHOW SNAPSHOTS IF NOT EMPTY)
+ Save Snapshots : Open snapshots with X (North) button instead of Game options ( which is now on long press A ).
=> Fix : Potential 'Black' gamelist after adding a game to favorites or returning from a game.

es-app/src/ApiSystem.cpp, es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-app/src/components/CarouselComponent.h, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/BasicGameListView.h, es-app/src/views/gamelist/CarouselGameListView.cpp, es-app/src/views/gamelist/CarouselGameListView.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h
- Content downloader : fix when package name contains a space
- Gamelist views : Invert SEARCH / RANDOM functions on north button 
- Rationalize help for gameslist views
- Fix : bad subfolder creation when using "parse gamelists only"
- Fix SystemData : Remove empty folders
=> Gamelist views : Invert SEARCH / RANDOM functions on north button + Fixes

es-app/src/ApiSystem.cpp
After discussing with the rest of the team, this seems to be a preferred solution (remove all cached pacman packages on refresh).
=> Clean-all when clicking on "refresh"

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp
If no timezone has been defined, try to autodetect the best timezone from the IP address, and otherwise default to "Europe/Paris" (default TZ until now). Requires scripts from https://github.com/batocera-linux/batocera.linux/pull/3882
=> Better timezone configuration

locale/CMakeLists.txt
ar    583 translated messages, 193 untranslated messages.
ca    180 translated messages, 596 untranslated messages.
cy_GB 725 translated messages, 51 untranslated messages.
de    773 translated messages, 3 untranslated messages.
el    2 translated messages, 774 untranslated messages.
es    776 translated messages.
es_MX 625 translated messages, 151 untranslated messages.
eu_ES 181 translated messages, 595 untranslated messages.
fr    771 translated messages, 5 untranslated messages.
hu    576 translated messages, 200 untranslated messages.
it    775 translated messages, 1 untranslated message.
ja_JP 771 translated messages, 5 untranslated messages.
ko    574 translated messages, 202 untranslated messages.
nb_NO 181 translated messages, 595 untranslated messages.
nl    529 translated …
=> nicer po output

es-app/src/Win32ApiSystem.cpp, es-app/src/Win32ApiSystem.h, es-app/src/guis/GuiMenu.cpp, es-core/src/Splash.cpp, es-core/src/ThemeData.cpp, es-core/src/platform.cpp, es-core/src/platform.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/renderers/Renderer_GLES20.cpp, es-core/src/resources/TextureData.cpp
NOTE : Please bump the theme, I added ifArch/ifNotArch attributes to deactivate some things for slow boards.
+ Add ES Video renderer information 
+ better organisation of information screen
+ Splash : Fix crash when gamesplash.xml is invalid 
+ Win32 only / Retrobat : if es-update script last line is a zip file, uncompress it using internal ES installer
=> Themes : Add support for ifArch/ifNotArch attributes -> Allow filtering elements/subsets by board to optimize slow boards

es-core/src/VolumeControl.cpp
otherwise... when restarting pw, it crashes
=> quit from thread should not call exit

es-core/src/utils/TimeUtil.cpp
Fix #943 (thanks @plaidman for flagging this!)
=> Fix: noon/midnight in 12:00 AM/PM format

es-app/src/FileData.cpp, es-app/src/FileFilterIndex.cpp, es-app/src/SystemData.cpp, es-app/src/guis/GuiGameOptions.cpp, es-app/src/guis/GuiGamelistFilter.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiScraperStart.cpp, es-app/src/services/HttpServerThread.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/CarouselGameListView.cpp, es-app/src/views/gamelist/DetailedContainer.cpp, es-app/src/views/gamelist/GameNameFormatter.cpp, es-app/src/views/gamelist/GridGameListView.cpp
Fixes Nintendo Entertainment System and Sega Megadrive not being shown in "GAMES SETTINGS" - "PER SYSTEM ADVANCED CONFIGURATION" menu.
Nintendo Entertainment System has the same group as Famicom Disk System and was hidden in "PER SYSTEM ADVANCED CONFIGURATION" menu. Settings for Famicom Disk System had no impact on Nintendo Entertainment System games because different setting prefixes in batocera.conf
=> Do not group systems for PER SYSTEM ADVANCED CONFIGURATION

es-app/src/FileSorts.cpp, es-app/src/FileSorts.h, es-app/src/guis/GuiMenu.cpp, es-core/src/Settings.cpp, es-core/src/Settings.h, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h
* This PR adds a new UI Setting option for ignoring leading articles when sorting.
* "The Legend of Zelda" is now sorted like "Legend of Zelda", "A Boy and His Blob" -> "Boy and His Blob", etc.
* I set the default value to `false` to maintain existing behavior.
* ~~The articles default to "a,an,the", but can be adjusted in `batocera.conf` if the user wishes.~~
* The articles can be defined per language
Thanks!
=> Add ui setting to ignore leading articles when sorting

es-core/src/Settings.cpp
Lower values cause slow loading of game images.
=> rpi1: MaxVRAM = 128

es-app/src/guis/GuiMenu.cpp
Bug:
1.- Set any game to be "Launched at startup" and save
2.- global.bootgame.cmd and global.bootgame.path are set
3.- Open another game advance options, do nothing, return to menu
4.- global.bootgame.cmd and global.bootgame.path are cleared
This PR fixes it by only running the save function if the value has changed.
=> FIX: bootgame was cleared by mistake

es-app/src/LibretroRatio.cpp
Collaborates with https://github.com/batocera-linux/batocera.linux/pull/4743 to add the "full" ratio as an option in EmulationStation. "Full" stretches the image to fill the screen.
=> Add "full" ratio as option

es-app/src/scrapers/ScreenScraper.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h
So they are…hashed before scrapping -> time to way is almost eternal....
=> Fix : getFileSize returns wrong size for >= 8Gb files

es-app/src/guis/GuiGameOptions.cpp, es-app/src/guis/GuiMenu.cpp
The string "EDIT PAD TO KEYBOARD CONFIGURATION" was too long to fit in the menu and was cut off. Changed to "EDIT PADTOKEY PROFILE" to properly fit. Same thing with "CREATE PADTOKEY PROFILE".
Made support file creation pop use consistent terminology, opted to use "create" verb. It also now mentions _where_ the file is created, reducing confusion.
=> update padtokey label so it fits and support file generation location

es-app/src/SystemData.cpp, es-app/src/SystemData.h
Allow features to be reused elsewhere without duplicating them multiple times.
Here's a sample of what can be achieved :
```
<features>
<sharedFeatures>
<feature name="INPUT DRIVER" value="input_driver" >
<choice name="SDL2" value="sdl2"/>
[...]
</feature>
</sharedFeatures>
<globalFeatures>
<sharedFeature value="input_driver" />
</globalFeatures>
<emulator name="libretro">
<sharedFeature name="input_driver"/>
[...]
<emulator name="pcsx2">
<sharedFeature value="input_driver"/>
[...]
```
=> es_features : Add shared features support ( reusability of features )

es-app/src/FileData.cpp, es-app/src/Gamelist.cpp, es-app/src/Gamelist.h, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/SaveStateRepository.cpp, es-app/src/SystemData.cpp, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/CarouselGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h
+ Scaper : Add bezel option to screenscraper
+ Gameinfo : Provide full paths
Win32/SaveStates : use modification date instead of creation time 
+ Grouped systems : Fix - unable to hide a system when it's grouped into another one + Fix group child system logo when showing folders
=> Scaper : Add bezel option to screenscraper + Gameinfo : Provide full paths

es-app/src/guis/GuiMenu.cpp
Allows the user to opt to use the original resolution + ratio of the image they have selected as the tattoo. "AUTO" behaviour is to resize to 225 px proportionately (similar to current live behaviour).
Also adds contingencies if the user tattoo is too large for the screen
and consistent terminology to some other items in the decorations submenu (so as not to confuse the term "overlay" (which is what RetroArch refers to bezels as sometimes) with "bezel").
Complements https://github.com/batocera-linux/batocera.linux/pull/5161
=> Add resize option to decorations submenu + minor fixes

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/SystemScreenSaver.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/DetailedContainer.cpp, es-core/src/Scripting.cpp, es-core/src/Scripting.h
This PR adds 2 new scripting events:
game-selected: fired when the cursor is on a game and when the screensaver selects a random game
system-selected: fired when the cursor is on a system
game-selected passes the system name, path to rom, and game name to fireEvent
system-selected passes the system name to fireEvent
Additionally, fireEvent was updated to accept an optional third argument. Arguments are also checked for empty strings and are dropped if empty.
=> Add game-selected and system-selected events

es-app/src/SaveState.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSaveState.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/HttpReq.cpp, es-core/src/SystemConf.cpp, es-core/src/SystemConf.h, es-core/src/components/OptionListComponent.h
- SaveStates : Split "AUTO SAVE/LOAD" option in two options : "AUTO SAVE/LOAD" & DISPLAY SAVE STATE MANAGER
- INCREMENTAL SAVESTATES option : Add "DISABLED - NEW GAME OVERWRITES CURRENT SLOT" value -> Using this will cause new games not to find the next free slot anymore.
- Win32/HttpReq : Fix wrong proxy server extraction in some cases
=> SaveStates : Split "AUTO SAVE/LOAD" option in two options 

es-core/CMakeLists.txt, es-core/src/renderers/Renderer.cpp, es-core/src/renderers/Renderer.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GL21.h, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/renderers/Renderer_GLES10.h, es-core/src/renderers/Renderer_GLES20.cpp, es-core/src/renderers/Renderer_GLES20.h
This allow multiple drivers ( for Windows mainly ), and set the Renderer to use with es_settings.cfg file
For Windows, you can add the following entries in es_settings. Renderers are :
`<string name="Renderer" value="OPENGL 2.1 / GLSL" />` 
-> default, used if "Renderer" is not defined
or
`<string name="Renderer" value="OPENGL 2.1" />` 
-> forces the old OpenGL driver
=> Refactored Renderer apis to use IRenderer interface. 

es-app/src/SystemScreenSaver.cpp
Fix slideshow and video screensavers with custom folders
ES crashed in slideshow and video screensavers with custom folders. 
Crash is since https://github.com/batocera-linux/batocera-emulationstation/pull/1075
@n-i-x @nadenislamarre @fabricecaruso
=> Fix slideshow and video screensavers with custom folders

es-core/src/AudioManager.cpp, es-core/src/AudioManager.h
I've changed the behaviour of the music player so it will keep a limited history of previously played songs in memory, and skip playing songs if they're in that list. So it will avoid situations where the current randomness is "not random enough" and repeats recent songs. I have had situations where songs have repeated many times and it gets annoying.
This solution isn't perfect but I think it does an adequate job of fixing this problem, can be easily removed later and adds very little overhead to the current system. It also works when per system music is enabled.
The history size is hardcoded, and I've just made a decision for it to be 40% of the size of the total song collection.
=> Track music history to stop songs replaying

es-core/src/components/TextEditComponent.cpp
This change makes it so when you're holding down left or right in a text input the cursor will stop blinking. The current behaviour is annoying because you can't see the cursor half the time and you miss your spot.
=> Don't blink cursor on key repeat

es-core/src/AudioManager.cpp
If an mp3 file has an id3 v1 song title at or over 30 characters the notification window will overflow into the next id3 fields trying to display it.
The files I was using actually also have v2 tags, the default behaviour of that app I used to set them was to do both. It might be better to prefer v2 tags if both exist.
=> Limit song title length sent to notification

es-app/src/FileData.cpp
After updating Scripting::fireEvent to support additional args, game-start was never updated to include more info. This PR fixes that.
=> Add game name to game-start event for pixelcade

es-core/src/Window.cpp
If the screensaver is active due to inactivity and the `/launch` API is called.  No 'launch' happens until a button is press or something is done to wake the device up.
When posting updates to the UI thread, check if the device is sleeping or in power save mode.  
- If UI is sleeping or in powersave: unset sleep and also unset the screensaver inactivity timeout.  
- Then send a 'refresh' message so UI is updated and launch event processed.
=> Fix /launch API not triggering when screensaver is active

es-app/src/views/gamelist/DetailedContainer.cpp, es-app/src/views/gamelist/DetailedContainer.h, es-core/src/GuiComponent.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/components/ImageComponent.cpp
**Theming : Per-game customization support**
First, declare the folder where per-game customisation are stored, in the view(s) you use : 
```
<view name="detailed">  
<gameextras name="gameextras">
<path>./../games/${system.theme}</path>
</gameextras>
```
You can define a folder per view, or use the same folder for all views.
In your theme create the folder ( ex : \games\fbneo for the provided sample )
Then create a xml theme file for the game, following one of this naming conventions :
- create a folder using the "rom" name, and place a theme.xml file in that folder ( ex : 1945kiii/theme.xml )
- create a folder using the "rom" crc32, and place a theme.xml file in that folder ( ex : 0B7A7EA5/theme.xml )
- create an xml file in the folder using the "rom" name  ( ex : 1945kiii.xml )
- …
=> Theming : Per-game customization support

es-app/src/guis/GuiUpdate.cpp
As it is right now, the "UPDATE IS READY" notification is too small to contain this string:
This shortens it to fit.
=> Shorten "REBOOT SYSTEM TO APPLY THE UPDATE" string

es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiNetPlaySettings.cpp, es-app/src/guis/GuiRetroAchievementsSettings.cpp, es-app/src/guis/GuiScraperSettings.cpp
This is a neater PR for https://github.com/batocera-linux/batocera-emulationstation/pull/1158 . For convenience, its description is below:
Clarity and label improvements
This makes some more dramatic changes and adds in a lot of description labels into the interface. I am aiming to get some feedback on this before committing it to master.
The objective of this PR are as follows:
* To make the menus more friendly for new users who may not have experienced emulation software before.
* Reduce redundancy in labelling.
* Explain what the settings do without ambiguity.
* Reorganise the controller settings to show that there's more than just player order settings.
Since most strings are new, it would be fine to put this in for the next immediate release. However, some strings (most important, …
=> Squashed commit of the following:

es-app/src/components/TextListComponent.h, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/GameNameFormatter.cpp, es-app/src/views/gamelist/GameNameFormatter.h, es-core/src/LocaleES.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h, es-core/src/components/VideoVlcComponent.cpp, es-core/src/components/VideoVlcComponent.h, es-core/src/renderers/GlExtensions.cpp, es-core/src/renderers/GlExtensions.h, es-core/src/renderers/Renderer.cpp, es-core/src/renderers/Renderer.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GL21.h, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/renderers/Renderer_GLES10.h, es-core/src/renderers/Renderer_GLES20.cpp, es-core/src/renderers/Renderer_GLES20.h, es-core/src/renderers/Shader.cpp, es-core/src/renderers/Shader.h, es-core/src/resources/Font.cpp, es-core/src/resources/Font.h, resources/shaders/negative.glsl, resources/shaders/scanlines.glsl
+ Add Theme support for image.saturation & video.saturation ( 0.0 -> grayscale to 1.0 -> normal )
+ Add Theme support for image.shader & video.shader : Allow use of external shaders in Themes.
+ Add custom scanlines shader in resources/shaders ( could be used to display a video or image with scanlines - see sample image )
+ Add Theme support for textlist.extraTextColor & textlist.extraTextSelectedColor ( extraText color is for texts located between [] or () which can now be displayed with a different color )
+ Add Gun icon on games supporting lightgun
=> OpenGL shaders : Better support & management

es-core/src/platform.cpp
=> Support Non-ASCII rom path in windows platform

es-app/src/guis/GuiRetroAchievementsSettings.cpp
This option was described incorrectly, there is no resetting of the achievements, it solely allows you to receive the unlock notification again and nothing else.
=> amend one incorrect string

es-app/src/SystemData.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/ThemeData.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/IList.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/VideoComponent.cpp, es-core/src/renderers/Renderer.cpp, es-core/src/renderers/Renderer.h, es-core/src/utils/MathExpr.cpp
- zIndex : Reorder parent's children when zIndex change ( due to storyboard animations )
- Add new Themes variables : 
screen.width, screen.height, screen.vertical (bool), screen.ratio (string, format 16/9, 4/3... see libretro ratio list )
- onclick : add new events :
Gamelist -> video, manual, map, cheevos, medias
SystemView -> cheevos
- ImageGrid : fix scroll pos when returning back from a child folder
=> Misc improvements & fixes

es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSaveState.cpp
Now uses a consistent terminology for savestates.
=> Update strings to refer to savestates consistently

es-core/src/AudioManager.cpp
I can't recall if there's any reason why we parsed ID3 tags v1 before v2 when both are available in an mp3. If anyone has an idea, please let me know.
Otherwise, more recent tags are probably a better choice (first, because 255 characters maximum are better than 30)
=> When mp3 have both tags, use ID3v2 rather than ID3v1.

es-app/src/guis/GuiMenu.cpp
Complement to https://github.com/batocera-linux/batocera.linux/pull/6811
"The video mode description says 'Force the emulator to run at this resolution', but that's not entirely true. The emulator's rendering resolution is what decides your game's resolution, the video mode is just the resolution of the signal sent to the display.
The reason for this change was a new user thinking that video mode was the option to change their rendering resolution. This change aims to improve the new user experience for this setting."
=> more accurate descriptive label for video mode

es-core/src/Window.cpp
Ignore initial SDL_MOUSEMOTION events with zero coordinates
Fixes https://github.com/batocera-linux/batocera.linux/issues/6920
=> Workaround for mouse cursor shown on start

es-app/src/RetroAchievements.cpp, es-app/src/RetroAchievements.h, es-app/src/guis/GuiRetroAchievements.cpp
By default, if you don't enable hardcore mode or use the save states like many users, points will always be accrued to "softcore points", not "points" any more, as RetroAchievements has now changed "points" to be hardcore-only. 
That means that without that PR, users will unlock cheevos, get the badges and so on, but their "points" would be stuck to 0. Now, we have a new line for softcore points to show progress.
=> Support for new hardcore/softcore points in RetroAchievements

resources/gungames.xml
Removing non exclusive gun games. Keep only true shooting / gun games. Those games won't work without setting them manually.
Plus, fixing Shootin' Putin light gun type.
=> Removing games with optional light gun support

es-app/src/guis/GuiMenu.cpp, es-core/src/Window.cpp
- normal : draw borders when required
- hidden : the border are not displayed (assume that there are provided by an other way like bezels)
- force  : force even if no gun requires it (or even no gun at all)
- gameonly : borders are not visible in es, just in game (for boards having a sinden gun alway plugged in)
=> sinden guns modes

es-app/src/ApiSystem.cpp
Check for the HTTP URL of Google instead of only relying on its DNS. This will improve the robustness of the tool and also how quickly it resolves (in my personal testing at least, pinging the http domain is 2ms quicker).
Related issue: https://github.com/batocera-linux/batocera-emulationstation/issues/1102
Also made the structure of the code more consistent with the rest of the file.
=> update ping utility

es-core/src/platform.cpp
The Linux kernel has drivers for standalone battery-monitoring hardware that does not show up in /sys/class/power_supply as a discrete battery device with "status" and "capacity" properties. For example, in my use case, I am using the LTC2941 fuel gauge and the generic "gpio-charger" driver to detect the presence of +5V on the USB charging port. The LTC2941 does not report "capacity" but it does report the current charge level and the max charge level of the battery. Meanwhile, the gpio-charger driver does report the charging status via a "status" property, but it's a separate device from the fuel gauge.
This PR adds support for such devices so that the battery status overlay works as intended. If I did it right, existing functionality is preserved for users without such hardware, or with …
=> Support battery readings from standalone fuel gauge and charger

es-app/src/services/HttpServerThread.cpp
- returns HTTP 200 if idle & json [ true ]. 
- returns HTTP 201 if not idle & json [ false ].
=> [HttpServer] Add /isIdle api to detect whether a game, a scrap, an update or an indexation is running

es-core/src/platform.cpp
This fixes a typo that broke battery detection, as discussed here: https://github.com/batocera-linux/batocera-emulationstation/pull/1311#issuecomment-1287104364
=> Fix battery detection typo

es-core/src/components/VideoVlcComponent.cpp, es-core/src/resources/TextureData.cpp
Ensure the old "plugins/gui/libqt4_plugin.dll" is not present anymore if libvlc.dll 3.x.x.x is installed
=> [Win32 only] Make VLC upgrade possible to VLC 3.x

es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/ThemeData.cpp, es-core/src/anim/ThemeAnimation.h, es-core/src/anim/ThemeStoryboard.cpp, es-core/src/anim/ThemeStoryboard.h
Warning : if you set sound to multiple controls ( `<control name="md_description, md_name [...]">` ) it will be played for every control at the same time... -> So use it on one control only !
```
<control name="md_description">
<storyboard>
<sound path="./../art/sounds/scroll.wav" at="1000"/> 
</storyboard>
</control>
```
=> [Storyboard] Add support for <sound path="XXX" at="1000"/> element in storyboards

es-app/src/CollectionSystemManager.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/views/SystemView.cpp
This adds an additional sort type to the Systems list, tentatively "Manufacturer and Type," internally "subgroup."
The sort method is different than Sort by Manufacturer in that within the manufacturer's systems they get sorted by type before year. So for example, Nintendo will list all their consoles from NES to Wii U, then handhelds from Game & Watch to 3DS. Sega will list their arcade systems, then consoles, then the Game Gear. Atari is consoles, then computers, then the Lynx.
It was requested on the Batocera Discord, and it does make logical sense as a sort method as it keeps similar systems grouped together. The one outlier in Batocera is that Windows is tagged as "pc" rather than "computer," so Microsoft will go MSX - XBox - Windows. If this gets merged, I'll re-tag it as computer.
=> Add Manufacturer & Type Sort

es-app/src/SystemData.cpp, es-core/src/components/BatteryIndicatorComponent.cpp
- Fix RetroAchievements indexing for Arduboy and WASM4
- For the future, add RetroAchievements for Megaduck
- Tiny fix (duplicate lines on empty battery icon)
=> Fix RetroAchievements for Arduboy and WASM4

es-app/src/guis/GuiKeyMappingEditor.cpp, es-app/src/guis/GuiMenu.cpp, es-core/src/InputConfig.cpp, es-core/src/guis/GuiInputConfig.cpp
Less dependent on the user knowing the layout of both the SNES and PS3/4 controller.
Uses the same co-ordinate system for face buttons as used throughout the rest of Batocera:
Replaces L1/R1 with Left shoulder/Right shoulder and L2/R2 with Left trigger/Right trigger.
Replaces L3/R3 with Left stick press/Right stick press.
Specifies the "up/down/left/right" are for the D-pad.
=> mapper input labels to be homogenuous

resources/gungames.xml
I'm excluding all non-true gun games like Dino Strike and Resident Evil - Dead Aim.
Don't merge until PCSX2 is bumped with the new native GunCon support.
=> Adding PS2 gun games (v37)

resources/gungames.xml
Don't merge until libretro-cap32 is bumped to today's version with the appropriate light gun rule (`phaser` & `gunstick` instead of `off`)
=> Adding GX4000/AmstradCPC gun games

locale/lang/de/LC_MESSAGES/emulationstation2.po
Someone accidentally added "KEIN SPLASH" which is only right for one specific menu.
=> Update DE locale

es-app/src/FileData.cpp, es-app/src/SystemData.cpp, es-core/src/utils/TimeUtil.cpp
modified es-app/src/FileData.cpp and es-app/src/SystemData.cpp
to include a resolve for the gametime metadata ticking over 24 hours.
Following on from the issue I raised here, https://github.com/batocera-linux/batocera-emulationstation/issues/1357
=> modified es-app/src/FileData.cpp and es-app/src/SystemData.cpp

es-app/src/components/ScraperSearchComponent.cpp, es-app/src/scrapers/HfsDBScraper.cpp, es-app/src/scrapers/HfsDBScraper.h, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h
With HFSDB, as we can perform only 2 request per minute, abandon search if the server's reponse is 429, if delay to wait is > 5 seconds when scrapping manually. If we don't do that, the screen can remain open 1 minute without doing anything
=> [HFSDB] Abandon manual search if the server's reponse is 429, if delay to wait is > 5 seconds

es-app/src/NetworkThread.cpp, es-app/src/Win32ApiSystem.cpp, es-core/src/InputManager.cpp
When SDL2.dll is at least 2.24 - instead of "batocera-padsinfo" script
=> [Win32 only] Update controllers battery levels using new SDL_JOYBATTERYUPDATED event

es-app/src/services/HttpApi.cpp, es-app/src/services/HttpApi.h, es-app/src/services/HttpServerThread.cpp
add web API /caps
returns ES capability info in JSON
frontend can understand (customised) ES features
and switch correctly.
=> [Suggestion] web frontend can look ES capability

resources/genres.xml
Fixed Problem:
genre list on ES GUI is disorderly
The way:
hand-sorting
(P.S.)
parent of Pachinko and Shooter Small are missing
and cannot sort
=> [Fix] genre list is sorted by parent

es-core/src/platform.cpp
Following a board renaming in batocera, this PR updates the getArchString() accordingly.
It tries first to read the /usr/share/batocera/batocera.arch file (only when not on Windows) and fallbacks to classic #ifdef implementation.
=> Update getArchString() function to match batocera board renaming

es-app/src/scrapers/HfsDBScraper.cpp
Add HfsDB PlatformID for ATARI_XE / xegs
=> Enable HfsDB as another scraper source for xegs

es-core/src/ThemeData.cpp, es-core/src/ThemeData.h
Exempl : lang='es_MX' or lang='pt_BR'
=> [Theming] Add optionnal support to fullname language in themes lang attribute

resources/gungames.xml
They work with Play! emulator in a separate collection named `namco2x6` (tested on v38 butterfly). The scraper doesn't work for that collection at the moment. But this is futureproof. Merge once the scraper works with the Namco 2x6 collection.
=> Adding Namco 2x6 gun games

es-core/src/AudioManager.cpp
Calculation for changing the music volume slider scale from LINEAR to LOGARITHMIC. 
Human hearing works on a logarithmic scale, so for example, 50% of perceived volume reduction in a numeric percentage would be roughly 66-67% of 100 on the music volume slider. I believe this is how the master volume slider works currently.
Currently the master slider and the volume slider's do NOT scale volume in the same manner. This should resolve that.
=> Logarithmic calculation for music volume

es-app/src/ApiSystem.cpp
Use pm-is-supported to check suspend support, making SUSPEND SYSTEM option available only when appropriate
=> Use pm-is-supported to check suspend support

es-core/src/components/MultiLineMenuEntry.cpp, es-core/src/components/TextComponent.cpp
[MultilineMenuEntry] Set main text as singleline
=> [TextComponent] Fix Y AutoCalcExtent when TextComponent is MultiLineType::SINGLELINE

es-core/src/InputManager.cpp
When starting Emulationstation with a gamepad connected and outside of Batocera this code is run: https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/InputManager.cpp#L419
This will crash because `rebuildAllJoysticks` is called in [`::init`](https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/InputManager.cpp#L78) before the keyboard is initialized and the called to `initialized` in [`writeDeviceConfig`](https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/InputManager.cpp#L925) [checks that it is initialized](https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/InputManager.cpp#L1044).
=> Fix crash at init when run outside of Batocera

resources/gungames.xml
Justifier has been added to pcsx_rearmed. With mednefen core, they are the only ones to have that native support (without patching the ROM).
Testing...
=> changing controller type for PSX light gun games

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/NetworkThread.cpp, es-app/src/NetworkThread.h, es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/gamelist/DetailedContainer.cpp, es-core/CMakeLists.txt, es-core/src/Window.cpp, es-core/src/components/BatteryIconComponent.cpp, es-core/src/components/BatteryIconComponent.h, es-core/src/components/BatteryTextComponent.cpp, es-core/src/components/BatteryTextComponent.h, es-core/src/components/ControllerActivityComponent.cpp, es-core/src/components/ControllerActivityComponent.h, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/IExternalActivity.h, es-core/src/components/NetworkIconComponent.cpp, es-core/src/components/NetworkIconComponent.h, es-core/src/renderers/Renderer.cpp, es-core/src/watchers/BatteryLevelWatcher.cpp, es-core/src/watchers/BatteryLevelWatcher.h, es-core/src/watchers/NetworkStateWatcher.cpp, es-core/src/watchers/NetworkStateWatcher.h, es-core/src/watchers/WatchersManager.cpp, es-core/src/watchers/WatchersManager.h, resources/shaders/blur.glsl
- [WatchersManager] WatchersManager checks for updates availability, machine battery level, pads battery level, network state & plane mode in a unified thread that notifies components when something changes. ( this avoids watching it in the UI thread as it works currently )
- [Lightgun] Don't show lightgun crosshairs during screensaver https://github.com/batocera-linux/batocera.linux/issues/10415
- [Win32] Fix SDL Window Styles for FullscreenBorderless
- [Shaders] Fix blur.glsl colorization
=> [WatchersManager] Use a unified thread to perform all watches 

es-app/src/main.cpp, es-core/src/renderers/Renderer_GLES20.cpp
=> [Win32] Port Win32 High CPU Usage fix from GL21 renderer to GLES20 renderer

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiInstallStart.cpp
A common source of user error when using the "INSTALL ON A NEW DISK"
feature is that the user guesses their architecture incorrectly.
With this change, if an installation architecture matches the
currently running board, it will be selected as default.
If no match is found, the previous behavior is retained.
=> Select running board as default installation target

es-core/src/VolumeControl.cpp
Should fix this one https://github.com/batocera-linux/batocera-emulationstation/issues/1563 v38 - Audio volume sets to 100% after reboot
=> 1563 - Audio volume sets to 100% after reboot

es-core/src/InputConfig.cpp, es-core/src/InputConfig.h, es-core/src/InputManager.cpp
the current default sort is random. prefer to sort according to hardware ports (mainly for cabinets having the same controllers for player 1 and 2)
device syspath for /dev/input/event7 is /sys/devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-1/1-1.2/1-1.2:1.0/0003:146B:0902.0012/input/input41/event7
device syspath for /dev/input/event15 is /sys/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-3/3-3:1.2/0003:28DE:1205.0003/input/input21/event15
device syspath for /dev/input/event17 is /sys/devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-1/1-1.1/1-1.1:1.0/0003:146B:0902.0011/input/input40/event17
device syspath for /dev/input/event18 is /sys/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:1/0005:2DC8:6100.0013/input/input42
=> default pad sort for udev on device ports

es-app/src/components/CarouselComponent.cpp, es-app/src/components/CarouselComponent.h, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-core/src/ThemeData.cpp
default is 0 : No space
1 -> apply the same space that exist between 2 inactive logos 2 -> apply the double
0.5 -> apply half...
=> [Carousel/Theming] Add "scaledLogoSpacing" element to define how the active scaled logo should be padded from other logos

es-app/src/EmulationStation.h, es-core/src/Window.cpp, es-core/src/components/PostProcessShaderComponent.cpp
+ use Blend::ONE to render postprocess shaders ( as we don't need transparency )
=> [PostProcess Shaders] Optimisations : Don't render bottom view if we have a Shader Texture Cache

resources/gungames.xml, resources/wheelgames.xml
- Initial optimization for Dreamcast, GameCube, N64
- More optimization for PS2
- Adding few more games
- Fixing some name orders in both GUN/WHEEL databases
=> Wheel optimization (part 2)

resources/gungames.xml
Making Wii gun games 100% playables with all controls required.
Removing Top Shot Dinosaur Hunter, not a gun game.
DO NOT MERGE YET.
Need first `tiltleft`, `tiltbackward`, `tiltforward`, duplication (one virtual gun button triggering two wii buttons at the same time) and emulated nunchuk enabled by default.
=> Fixing all Wii gun mapping

resources/gamesdb.xml
Update gamesdb.xml to include native widescreen support for sega games. Systems: X32, Saturn, and Dreamcast.
=> SegaGames-Update

resources/wheelgames.xml
`controller="1"` means a controller must be set to port 1 
`port1="2"` means the wheel (on port 1) must be set to port 2 
Default N64 and Saturn mapping need to be redone.
Naomi/Naomi2/Atomiswave mapping need to be done in configgen.
=> Optimizing wheels (part 3 - remake)

es-app/src/views/ViewController.cpp
Otherwise, when there's a game description, it plays back over the launched game itself (with its own sounds and music...).
=> Silence TextToSpeech when launching a game

es-app/src/guis/GuiControllersSettings.cpp, es-core/src/InputManager.cpp, es-core/src/Settings.cpp, locale/emulationstation2.pot
Enables the ability to turn off the controller connected/disconnected notifications.
I have scripts that dynamically create controllers via `evsieve` when games launch and exit, and the notification popups are distracting.  This setting gives users the ability to turn off those notifications if desired.
=> Toggle visibility of controller notifications

es-core/src/SystemConf.cpp, es-core/src/SystemConf.h
Currently whenever a `batocera.conf` setting is changed in ES all `batocera.conf` settings **modified outside ES** are reverted to the values they had when ES was started.
This PR prevents overwriting all config in `batocera.conf` wheneven one or more config values are changed in ES. With this PR ES updates in `batocera.conf` only those settings that were changed in ES.
Although this is a bugfix I think it would be better to test it for a while (to review and merge it when development of Batocera v40 will start).
=> [v40] Save only changed config

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiControllersSettings.cpp, es-app/src/guis/GuiMenu.cpp
Add settings "ENABLE BLUETOOTH" and "ENABLE PS3 CONTROLLER SUPPORT" to "CONTROLLER & BLUETOOTH SETTINGS".
This requires https://github.com/batocera-linux/batocera.linux/pull/11003
=> [v40] Add settings for disabling BT and PS3 controllers

resources/gamesdb.xml
Optimizing arcades rotation degrees. Not perfect science, mainly based on arcade manuals, real-world steering knowledge (potentiometer, paddle, etc) and testing.
Infinite turn wheel games like "Championship Sprint" are set to 360 to keep it playable for high end modern steering wheel. Remove it for DD (direct drive) wheels (e.g.: MOZA Racing R9) to get full accuracy.
=> Steering wheel optimization (part 5)

resources/gamesdb.xml
This is not required, cores and emulator are already correctly mapped by default for neGcon device. Keeping this will confuse more than anything the configgen.
=> delete useless negcon controls (psx)

resources/gamesdb.xml
Non-HD and Singe2 ROMs from the official Hypseus Singe Data repository are not present in the game database since its merged. This will add their compatibility to be properly detected as gun games.
=> Add Daphne non-hd/Singe 2 gun games compatibility

es-app/src/ApiSystem.cpp
Avoids showing `America/Argentina` etc which is not a valid timezone.
=> continents were still showing countries

es-app/src/guis/GuiNetPlaySettings.cpp
Add option in netplay settings:
The setting of custom server will be stored in es_config as "global.netplay.customserver".
Example of values generated:
`	<string name="global.netplay.customserver" value="192.168.0.9" />
<string name="global.netplay.nickname" value="Ben" />
<string name="global.netplay.port" value="55435" />
<string name="global.netplay.relay" value="custom" />`
=> Add custom relay server option to netplay

es-app/src/guis/GuiMenu.cpp, es-app/src/views/ViewController.cpp, es-core/src/components/ControllerActivityComponent.cpp
Add new game launch animations fast fade and fast slide which are twice as fast as the normal fade and slide.
Also changes the controller activity color to a different shade of blue that matches the other blue colors in the default carbon theme, as well as having a better contrast in mostly white and black backgrounds. Examples seen here: 
new color: https://convertingcolors.com/hex-color-3675CA.html?search=Hex(3675CA)
original color: https://convertingcolors.com/hex-color-000066.html?search=Hex(000066)
=> Add fast game launch animations / update controller activity color

es-app/src/views/ViewController.cpp
Spectator mode is possible even if core does not support netplay.
If isNetplayActivated makes the netPlayMode=DISABLED, it will be impossible to create or join in spectator mode.
=> Remove isNetplayActivated check

es-app/src/ThreadedHasher.cpp, es-app/src/guis/GuiHashStart.cpp
Since https://github.com/batocera-linux/batocera-emulationstation/pull/1799
The Hasher now computes the CRC for the games in every system, even if they don't support NetPlay.
-> The CRC fails for systems where games are directories (ps3, teknoparrot, dos), and it tries to re-index those files everytime ES starts.
Revert changes and limit indexation to systems that really support Netplay.
=> [Netplay] Hasher now computes the CRC for every system, even if they don't support NetPlay.

es-app/src/ApiSystem.cpp
For example when getting into the Settings menu.
Longer term, I think we should remove the /sys/class/ led handling from ES, but there are other changes in the kernel for non x86_64 in flight, let's wait until this settles down.
=> Prevent the LED sliders from being polluted by the LED daemon

es-app/src/FileData.cpp, es-app/src/guis/GuiNetPlay.cpp, es-app/src/views/ViewController.cpp
- The behavior differs across cores. For example:
- **Gambatte**:
- core_info NetPlay support as `false`.
- However, it can still run in **WATCH mode (SPECTATOR)**.
- **PCSX ReARMed**:
- Also reports NetPlay support as `false`.
- Neither allows WATCH mode nor runs at all.
- This will remain as-is until RetroArch's `core_info` defines NetPlay support more granularly, such as:
- `NetPlay support (SPECTATOR ONLY)`
- `NetPlay support (FULL PLAY)`
=> [NetPlay] Revert to checking isNetplaySupported() during NetPlay.

es-app/src/FileData.cpp, es-app/src/FileData.h
- Use iter_swap/pop_back idiom to improve FolderData::removeChild() performance
- Re-order deletions to take advantage of iter_swap/pop_back idiom
- Add FolderData::bulkRemoveChildren() and use it for removal of virtual folders
- Prevent inefficient unlinking of child files from a folder being destroyed
=> Improve destructor performance by 97% on very large folders

es-app/src/SystemData.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-core/src/Settings.cpp, es-core/src/Settings.h
When a group has only 1 active child system, this option allows not to create the group, but leave the system as is.
=> Add new option : DON'T SHOW GROUPS WITH ONY ONE SYSTEM

resources/gamesdb.xml
I'm just adding missing ones from MAME database. Most of them are already added. This is futureproof until MAME gets proper dumps and names:
-`hdkotr` for `Harley-Davidson: King of the Road`
-`hotd4sp` for `The House of the Dead 4 - Special`
-`hummer` for `Hummer`
-`hummerxt` for `Hummer Extreme Edition` (known as `Hummer Extreme` in MAME database) 
-`initiad4exp` for `Initial D Arcade Stage 4 (Export)` 
-`initiad5` for `Initial D Arcade Stage 5`
-`letsgojusp` for `Let's Go Jungle! Special`
-`rtuned` for `R-Tuned: Ultimate Street Racing`
=> Add Sega Lindbergh gun&wheel games

es-app/src/scrapers/ScreenScraper.cpp, es-core/src/GunManager.cpp
@nadenislamarre : can you validate this PR ?
=> Add ps4 screenscraper ID + win32 gun models in gunmanager

es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiGeneralScreensaverOptions.cpp, es-core/src/Settings.cpp
- Added SHOW DATE TIME option to toggle date and time display.
- Select the display format using DATE FORMAT and TIME FORMAT options.
- This feature works with both RANDOM VIDEO and SLIDESHOW modes.
=> [Screensaver] Add Date Time display

es-app/src/guis/GuiNetPlay.cpp
https://github.com/user-attachments/assets/d3f55bc5-a421-4763-8a5a-efdf144804be
Left: Current version, Right: Improved version.
Both have the same game_list size (16017),
and the Netplay lobby loading speed has been improved using futures.
Building a cache using Crc32 or name in FileData.cpp would be faster,
but due to concerns about performance on low-end devices, futures were used instead.
=> [Netplay] lobby loading speed using futures

es-core/src/components/ComponentGrid.cpp, es-core/src/components/ComponentGrid.h, es-core/src/guis/GuiTextEditPopupKeyboard.cpp
When using the PopupKeyboard,
if you start at the blue position and move the cursor, it functions normally.
However, if you start at the red position and attempt to move the cursor, it does not move at all.
This issue appears to occur when the cursorGridEntry's dim is greater than 1.
=> [PopupKeyboard] Cursor move bug fix

es-core/src/renderers/Renderer_GLES20.cpp
When the game is launched and then exited back to ES, the font of the popupkeyboard becomes distorted.
Vertical lines appear on the letters Q, A, and S.
This issue occurs when built with GLES20.
Original issue from: https://github.com/EmuELEC/EmuELEC/issues/878
Original PR: https://github.com/EmuELEC/emuelec-emulationstation/pull/100
=> Fontface Artifact Fix

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/guis/GuiGameOptions.cpp, es-app/src/guis/GuiNetPlay.cpp, es-app/src/guis/GuiNetPlay.h, es-app/src/guis/GuiNetPlaySettings.cpp, es-app/src/views/ViewController.cpp, es-core/src/Settings.cpp, es-core/src/Settings.h
It seems that no one is interested in this feature even in the new release, and it rather causes fragmented approaches to Netplay access, leading to confusion.
I have reverted #1799 and modified it to enable only the host option with the existing `netplay_public_announce` setting.
And a default value is set if the `netplay.nickname` is empty.
I apologize for bothering the Batocera team.
Feel free to let me know if there are any parts that need to be revised.
=> [Netplay] Reverted #1799 causing fragmentation

es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiGamelistOptions.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/components/TextEditComponent.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.h, es-core/src/resources/Font.cpp, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h
Korean(Hangul) input is now supported, and the altedShifted state has been added, allowing for more diverse input.
=> [PopupKeyboard] Add Korean & 4th Layout & fix Korean render bug & Unicode support for "Jump to game beginning with the letter"

es-app/src/guis/GuiCollectionSystemsOptions.cpp
Hi.
I observed that when two systems share the same `<fullName>`, they get automatically hidden upon changing the settings, despite not being explicitly unchecked from the list of systems to hide.
This is a small inconvenience but this surprised me, as I was not expecting my systems to disappear this way (it's not uncommon to share the same "full names" for US/JP versions for example).
The fix implemented here is quite straightforward: duplicates should not be removed when listing systems by their full name in the settings. We could also imagine a disambiguation display instead of duplicates.
Before:
https://github.com/user-attachments/assets/90c5868b-8bd5-4641-99a2-6a105ce5a27e
After:
https://github.com/user-attachments/assets/9adb22f6-7a10-4394-bbd8-e523e2844fd7
=> Fix systems automatically hidden when closing settings

es-app/src/guis/GuiNetPlay.cpp, es-app/src/guis/GuiNetPlay.h
Support browsing RetroArch games in the lobby within the same network.
These games are added to the LAN GAMES group, while games retrieved from lobby.libretro.com are added to the ONLINE GAMES group.
=> [NetPlay] Add Lan game search in lobby

es-app/src/guis/GuiNetPlay.cpp, es-app/src/guis/GuiNetPlaySettings.cpp, es-app/src/views/ViewController.cpp, es-core/src/Settings.cpp, es-core/src/Settings.h
AUTOMATICALLY CREATE LOBBY
Starts the game in host mode automatically when launched.
This option is disabled by default.
from: https://github.com/batocera-linux/batocera-emulationstation/pull/1887
SHOW RELAY SERVER GAMES ONLY
Displays only servers that use a relay server in the lobby.
This option is not needed for LAN play.
Additionally, it now calls the function earlier than `getFileData`, resulting in faster lobby loading.
=> [NetPlay] Added Netplay options: Auto Lobby & Relay Filter

es-core/src/resources/TextureData.cpp
this fixes "bad" video, like an empty file with extension mkv
blocking the es boot.
i don't know if a sleep 1ms is required or not in the loop.
a similar problem occurs when trying to play the video, but i don't manage to fix. at least, now it is limited on watching the video.
=> fix: infinite video loop

es-core/src/Scripting.cpp
See Issue : https://github.com/batocera-linux/batocera-emulationstation/issues/1772
=> [Win32/Scripting] Quit event not fired because of an async call

es-app/src/views/gamelist/DetailedContainer.cpp, es-app/src/views/gamelist/DetailedContainer.h, es-core/src/BindingManager.cpp, es-core/src/BindingManager.h
https://github.com/batocera-linux/batocera-emulationstation/issues/1925
You can set the path this way : 
<path>"${themePath}/games/" + {game:system:theme}</path>
I added the ability to provide the full xml file name. Like this :
<path>"${themePath}/games/" + {game:system:theme} + "/" + {game:crc32} + ".xml"</path>
=> [Theming] Support for dynamic expression in gameextras.path

es-app/src/guis/GuiNetPlaySettings.cpp, es-app/src/guis/GuiNetPlaySettings.h, resources/community_relay_servers.xml
Batocera currently provides RetroArch’s official relay servers as options for netplay.
This update adds support for user community relay servers, allowing additional community-hosted relays to be included.
I have added a relay server for Korean players (SEOUL) as the first community option, and I hope this opens the door for more countries to add their own in the future.
from https://github.com/knulli-cfw/batocera-emulationstation/pull/51
=> Add user community relay server feature with SEOUL as the first preset

es-core/src/utils/TimeUtil.cpp
Resolved the following warning
```
es-core/src/utils/TimeUtil.cpp:4:22: warning: extra tokens at end of #include directive
```
=> silence warnings
