locale/lang/ko/LC_MESSAGES/emulationstation2.po
=> update ko lang

locale/lang/ko/LC_MESSAGES/emulationstation2.po
Last update of Korean translation
=> Last update of Korean translation

es-app/src/guis/GuiScraperStart.cpp, es-app/src/scrapers/ScreenscraperScraper.cpp
Leaving the option "use composed visual" as default.
=> Use composed visual

locale/lang/pt_PT/LC_MESSAGES/emulationstation2.po
-Updated by @coiotato
https://github.com/coiotato/
=> Update pt_PT translation

es-core/src/Window.cpp, es-core/src/Window.h
=> pad: blue color to recognize the hotkey

es-core/src/Window.cpp
=> Little fix

es-app/src/MetaData.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMetaDataEd.cpp, es-core/src/RecalboxConf.cpp
=> default options

es-app/src/RecalboxSystem.cpp
=> fping for timeout

es-app/src/guis/GuiMenu.cpp
=> bezel: fix the default value

es-app/src/views/SystemView.cpp, es-core/src/InputConfig.cpp, es-core/src/InputConfig.h
=> pads: allow to move joystick1 pad to change system

es-app/src/RecalboxSystem.cpp, es-app/src/guis/GuiMenu.cpp, es-core/src/AudioManager.cpp, es-core/src/RecalboxConf.cpp, es-core/src/platform.cpp
=> remove_rbshare

es-app/src/guis/GuiMenu.cpp, es-core/src/AudioManager.cpp
=> rename share_init to initdata

es-core/src/RecalboxConf.cpp
=> es: prefer # for comment in .conf

es-core/src/components/OptionListComponent.h
=> fix empty lists

es-app/src/guis/GuiInstallStart.cpp
=> feat: inform at installation that network is required is no arch is found

es-app/src/guis/GuiMenu.cpp
=> fix emulator/core option saving

es-app/src/RecalboxSystem.cpp
=> fix kodi call

es-app/src/RecalboxSystem.cpp, es-app/src/guis/GuiMenu.cpp
=> fix sound menu

es-core/src/InputManager.cpp
=> fix es crash on some joystick events

es-app/src/guis/GuiMenu.cpp, es-core/src/InputManager.h
=> sdl209: fix crash on joysticks

es-app/src/guis/GuiMenu.cpp
=> add auto to shaders

locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po
=> pt_BR: update

locale/lang/pt_PT/LC_MESSAGES/emulationstation2.po
Translated by Claudio Monteiro (coiotato)
=> pt_PT: update by Claudio Monteiro (coiotato)

locale/lang/pt_PT/LC_MESSAGES/emulationstation2.po
=> fix: pt_PT

es-app/CMakeLists.txt, es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiThemeInstall.cpp, es-app/src/guis/GuiThemeInstall.h, es-app/src/guis/GuiThemeInstallStart.cpp, es-app/src/guis/GuiThemeInstallStart.h
Requires the updated `batocera-es-theme` script.
=> New theme installer

es-app/src/guis/GuiMenu.cpp
See the corresponding PR in batocera.linux for shaders configuration
=> Introduced "enhanced" shaders mode for #5.23

es-app/src/views/SystemView.cpp, es-core/src/components/VideoComponent.cpp
=> fix menu help buttons

es-app/src/CollectionSystemManager.cpp
Source: https://github.com/RetroPie/EmulationStation/commit/573cd4cdd56f09ff6a27a552093b63906b919ed9
Credits: @cmitu
=> Fix 'Last Played' collection crash.

es-app/src/views/gamelist/ISimpleGameListView.cpp
Had been broken a few months back
Source: https://github.com/RetroPie/EmulationStation/commit/1b06df1572fcdae21663aa138e1366d7d7714c42
Credits: @pjft
=> Fix Kiosk Favorites not registering

es-app/src/FileData.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp
=> enable collections

es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h
=> feat: new game options

locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po
=> update: pt_BR

README.md
=> add: dependency

es-app/src/scrapers/GamesDBJSONScraperResources.cpp
*New Public API key specially for the Batocera.linux project
-Special thanks to Leo and TheGamesDB project
=> Scraper: New API Key for TheGamesDB

es-core/src/Window.cpp
=> clock: color

es-core/src/AudioManager.cpp, es-core/src/Window.cpp, es-core/src/Window.h
Fix for info popup not showing
Fix for FadeOut not working anymore
Fix for potential crash ( deleting a null pointer. not safe depending on the compiler ) with info popup
=> Fix for info popup not showing & FadeOut not working anymore

es-app/src/guis/GuiMenu.cpp, es-core/src/AudioManager.cpp, es-core/src/AudioManager.h, es-core/src/Sound.cpp
- Fix a crash when returning from a game when "EnableSounds" is true
- Restore option "ENABLE NAVIGATION SOUNDS" in menus.
=> AudioManager support & fixes with Navigation sounds

es-app/src/guis/GuiBezelInstallStart.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiGamelistFilter.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiScraperStart.cpp, es-app/src/guis/GuiScreensaverOptions.cpp, es-app/src/guis/GuiSettings.cpp, es-app/src/guis/GuiSystemsHide.cpp, es-app/src/guis/GuiThemeInstallStart.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-core/src/Window.cpp, es-core/src/components/MenuComponent.cpp, es-core/src/components/OptionListComponent.h, es-core/src/guis/GuiTextEditPopupKeyboard.cpp, es-core/src/renderers/Renderer.cpp, es-core/src/renderers/Renderer.h, es-core/src/resources/Font.cpp, es-core/src/resources/Font.h
Small Screen / GPI : Show menus in fullscreen & scaled (also hide hel…
Themings : Fix subset crash if one subset is missing + show progress when changing a theme.
Options : add Developper submenu in system options.
=> FullScreen Menus for GPI

es-app/src/views/gamelist/DetailedGameListView.cpp
=> fix rpi compilation

CMakeLists.txt
=> option cec on/off

es-app/src/guis/GuiMenu.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/IGameListView.cpp, es-app/src/views/gamelist/IGameListView.h, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageComponent.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h
Enhanced animated grid view, with labels, auto layout, and padding.
+ added support for attribute tinyScreen on view elements for gpi
=> Enhanced Grid view

es-app/src/ApiSystem.cpp, es-app/src/SystemData.cpp, es-app/src/guis/GuiBackupStart.cpp, es-app/src/guis/GuiInstallStart.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiThemeInstall.cpp, es-app/src/guis/GuiThemeInstall.h, es-app/src/guis/GuiThemeInstallStart.cpp, es-app/src/guis/GuiThemeInstallStart.h, es-app/src/main.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/BasicGameListView.h, es-app/src/views/gamelist/DetailedGameListView.h, es-app/src/views/gamelist/VideoGameListView.h, es-core/src/Settings.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/Window.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/HelpComponent.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h, es-core/src/renderers/Renderer.cpp, es-core/src/renderers/Renderer.h
- UI : Added new option START ON GAMELIST 
- ImageComponent : Support for reflexion element in themes
- Themes : Support for custom views
- Theme subsets : better management
- ThemeData : Support tinyscreen attribute in includes
- Fix crash when theme folder don't contains theme.xml file 
- ThemeData/ImageComponent : minSize attribute was not supported 
- Theme installer : Brand new look
=> Misc Theming & bugfixes

es-core/src/LocaleES.h, es-core/src/guis/GuiTextEditPopupKeyboard.cpp
Leads to chinese characters instead of à, â, é....
=> fix GuiTextEditPopupKeyboard bad encoding of file

es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-core/src/utils/StringUtil.cpp
=> fix linux compilation

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/guis/GuiMenu.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-core/src/SystemConf.cpp, es-core/src/ThemeData.cpp
- Fixed Theme configuration not appearing and/or crashing
- Fixed Specific game config : GAME RATIO & VIDEO MODE were not saved
- Recent collection : very slow loading when item count > 50 ( when > 50 have been played, it reloaded the full gamelist for each removed item )
=> Fixes : Theme configuration & SpecificConfiguration

es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSettings.cpp, es-app/src/guis/GuiSettings.h, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-core/src/ThemeData.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/components/VideoVlcComponent.cpp, es-core/src/resources/TextureDataManager.cpp, es-core/src/resources/TextureResource.cpp
- ThemeData : Support for ifHelpPrompts attribute -> Theming can know if help is visible & adapt.
- Themes : Added option RESET GAMELIST CUSTOMISATIONS, to reset per system customisations.
- Vlc Video : Secured mMedia pointer
- ViewController : rendering optimisation
- Main : Log signals
=> ThemeData : Support for ifHelpPrompts & Added option RESET GAMELIST CUSTOMISATIONS

es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/BasicGameListView.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/IGameListView.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/components/IList.h
The current Retropie algorithm is currently too slow when there is a lot of games.
=> GameList options  reviewed "games first letter" computing

es-app/src/NetworkThread.cpp, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiScraperStart.cpp, es-app/src/main.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/ViewController.cpp, es-core/src/AudioManager.cpp, es-core/src/AudioManager.h, es-core/src/Settings.cpp, es-core/src/Window.cpp, es-core/src/components/BusyComponent.cpp, es-core/src/components/SliderComponent.cpp, es-core/src/components/SliderComponent.h
- AudioManager : Add support for theme musics.
- Scraper : Download medias in a queue 
- Scraper : hidden old "automatic" scrap mode -> replaced by unchecking "let user decide conflict" by default
- Scraper : display what media is currently downloading in busycomponent.
- Scraper : don't download thumb in parallell in automatic scrap mode -> Show the first downloaded media.
=> AudioManager : Add support for theme musics + Scraper enhancements

es-app/CMakeLists.txt
=> fix es compilation

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/FileData.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiUpdate.cpp, es-app/src/guis/GuiUpdate.h, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/ThreadedScraper.cpp, es-app/src/scrapers/ThreadedScraper.h, es-core/CMakeLists.txt, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/AsyncNotificationComponent.cpp, es-core/src/components/AsyncNotificationComponent.h
+ HttpReq : Stop downloading content in memory -> use a binary temp file in /tmp/ instead.
+ Make Themes downloader work on Windows
=> Updates : Run updates download & unpack in background thread.

es-app/src/guis/GuiBezelInstallStart.cpp, es-app/src/guis/GuiThemeInstallStart.cpp
=> fix: compilation

es-core/src/components/VideoVlcComponent.cpp, es-core/src/components/VideoVlcComponent.h
Should be smoother on platforms like RPI
=> Vlc video : double buffering

es-app/src/guis/GuiMenu.cpp, es-core/src/Scripting.cpp
=> Retroachivements : use normal font + support "iconRetroachievements" in themes

es-app/src/ApiSystem.cpp, es-app/src/CollectionSystemManager.cpp, es-app/src/FileFilterIndex.cpp, es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiSettings.h, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/ViewController.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h, es-core/src/components/OptionListComponent.h, es-core/src/components/VideoVlcComponent.cpp
- Vlc / testing purposes : use vlc.options in batocera.conf to push options to libvlc_media_add_option.
- SystemData : Avoid enumerating every file to count them when scrolling in systemView.
- Allow carousel.systemInfoDelay in themes
- Vlc RPI : Temporary size limit of videos 400x300 when video vram parameter is used ( testing purpose )
=> Decorations : Show previews in menu.

locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po
=> fix: pt_BR

es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiSettings.cpp, es-app/src/guis/GuiSettings.h, es-app/src/views/SystemView.cpp, es-core/src/ThemeData.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h
Image element :
- reflexionOnFrame : boolean. Indicates the reflexion position should be based on the source rectangle and not the image's bottom.
- horizontalAlignment : center, top, bottom. 
- verticalAlignment : center, left, right.
- flipX and flipY : boolean. Flips the image.
+ Decorations : size image from screen resolution.
+ Button Select Quit menu : Close menu with select button...
=> Themes : Added elements 

es-core/src/CECInput.cpp, es-core/src/CECInput.h, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/OptionListComponent.h
+  fix for gridView : marquees are flickering / reloading when scrolling up.
=> CECInput : potential SEGV

es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiMetaDataEd.cpp, es-app/src/guis/GuiSlideshowScreensaverOptions.cpp, es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-core/src/Settings.cpp, es-core/src/components/SwitchComponent.cpp, es-core/src/components/SwitchComponent.h, es-core/src/components/VideoVlcComponent.cpp
- Add option to display marquee in screensaver instead of game name.
- Add option to add random decoration in screensaver.
- Screenscraper : Manual scrapping : use jeuInfos before trying ( automatically ) jeuRecherche ( if no result )
- ScreenScraper : Fix atari800 platform ID.
=> ScreenSaver : better video screensaver with game & system name.

es-app/src/SystemScreenSaver.cpp, es-app/src/views/SystemView.cpp
+ Fix immediate mode for game count
=> VLC VideoScreenSaver : RPI Crash fix 

es-app/src/SystemScreenSaver.cpp, es-core/CMakeLists.txt, es-core/src/ThemeData.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/ControllerActivityComponent.cpp, es-core/src/components/ControllerActivityComponent.h, es-core/src/components/VideoComponent.cpp
+ ScreenSaver fixes ( decoration layouts / subtitle folder )
=> Controller Activity : rewritten as a themable component.

es-app/src/ApiSystem.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSlideshowScreensaverOptions.cpp, es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-core/src/Settings.cpp, es-core/src/utils/FileSystemUtil.cpp
- ScreenSaver : set decorations by system, random or none
- Windows only themes/bezel downloader : refactorings
- Windows only : custom collection paths fix.
=> CONTROLLERS SETTINGS : Crash when resetting a controller to DEFAULT

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp
+ ApiSystem : Add CRC32 computations using 7zr -> Will be usefull for scraping & netplay
=>  Music starts before /emulationstation.ready flag 

GAMELISTS.md, README.md, THEMES.md, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/main.cpp, es-core/src/HttpReq.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoVlcComponent.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.cpp, es-core/src/guis/GuiTextEditPopupKeyboard.h
- VideoComponent : Sometimes, video starts if the view has just been hidden (at end delay), and plays in background
- CrashFix when no controllers are configured 
- Scraper : HttpReq ignores http error codes
- OSK : Add x pad button to "reset" & validate ( useful for text filters ) 
- Localisation of customviews ( using variables ) 
+ Update Themes & general documentations
=> BugFixes + Update Themes documentation

es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/DetailedGameListView.h, es-app/src/views/gamelist/VideoGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.h
- Fix : SystemView can crashes when using L/R buttons when < 10 systems
- Game views : add support for md_thumbnail to display <thumbnail> image
=>  Fix : SystemView can crashes when using L/R buttons when < 10 systems

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/guis/GuiGamelistOptions.cpp, es-core/src/Settings.cpp
Usefull for systems like scrummvm that need subfolder containing only 1 game.
=> Splitted "SHOW FOLDERS" option in 3 modes : always, never and "having multiple games" 

es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/ScreenScraper.h, es-app/src/scrapers/ThreadedScraper.cpp, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h
- Added management for Http error 246 BLACKLISTED. If we are blacklisted one day we'll know explicitely.
=> ScreenScraper : Added Batocera's own ApiKey

es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/ScreenScraper.cpp
+ScreenScraper video scrap : Preferer new "video-normalized" format
=> Crash fix loading RetroAchievements

locale/lang/zh_CN/LC_MESSAGES/emulationstation2.po
Translate all untranslated items.
=> Update ZH_CN emulationstation2.po

es-app/src/guis/GuiMenu.cpp
Added the ES menu entries for https://github.com/batocera-linux/batocera.linux/pull/1049 (please merge the two PRs at the same time!).
=> Added "zfast" and "flatten-glow" shader sets.

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/FileFilterIndex.cpp, es-app/src/FileSorts.cpp, es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiScraperMulti.cpp, es-app/src/guis/GuiScraperStart.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/ThreadedScraper.cpp, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/AsyncHandle.h, es-core/src/HttpReq.h, es-core/src/MameNames.cpp, es-core/src/MameNames.h, es-core/src/ThemeData.cpp, es-core/src/utils/FileSystemUtil.cpp
- Optimized  use of mame names
- Scaper : Fixes + screenscraper http 400 management
- Windows : use FindFirstFileExW to speed up directory enumerations
=> Perfs/Memory : Optimized Collections loading & memory usage

locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po
=> Small fix on pt_BR emulationstation2.po

locale/lang/pl/LC_MESSAGES/emulationstation2.po
minor update to the Polish translation
=> updates Polish translation

es-app/src/ApiSystem.cpp
=> update bt pair command

es-app/src/SystemScreenSaver.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSettings.h, es-core/src/LocaleES.cpp, es-core/src/components/ComponentList.h, es-core/src/components/MenuComponent.cpp, es-core/src/components/MenuComponent.h
+ Add "Launch Screensaver" option in "exit menu"
=> Fix : Music not coming back after video screensaver when video audio is active

es-app/src/ApiSystem.cpp, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/guis/GuiBezelInstallStart.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiCollectionSystemsOptions.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiSettings.h, es-app/src/guis/GuiThemeInstallStart.cpp, es-app/src/guis/GuiThemeInstallStart.h, es-core/src/components/DateTimeComponent.cpp, es-core/src/components/DateTimeEditComponent.cpp, es-core/src/components/MenuComponent.cpp, es-core/src/components/MenuComponent.h
+ Menus refactorings & reorganisation (phase 1) 
+ Fix : Fix LocalArt setting + "unknown" is displayed when no metadata
=>  Retroachievement / Bezel : Revamped UI using menu Subtitles 

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSettings.h, es-core/src/components/MenuComponent.cpp, es-core/src/components/MenuComponent.h
Need to merged in sync with PR #1064 from lbrpdx :
https://github.com/batocera-linux/batocera.linux/pull/1064
=> RetroAchievements v2

es-core/src/ThemeData.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h
usable in gridviews to scroll too long texts
=> TextComponent : Add "autoScroll" property for single line texts

es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/ThemeData.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/NinePatchComponent.cpp, es-core/src/components/TextComponent.cpp
gridtile.padding : changed to NORMALIZED_RECT to support 4 points padding
Ninepatch : support color animation when texture set
=> Gridview : text, marquee, favorite & overlay can now be zOrdered

es-app/src/FileData.cpp, es-app/src/Gamelist.cpp, es-app/src/MetaData.h, es-app/src/guis/GuiMenu.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/ViewController.cpp, es-core/src/Settings.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h
SystemView : reworked Fade transition 
GameList : Small optimisation when saving
=>  SystemView : Add support for 'defaultTransition' and 'scrollSound' + reworked Fade transition 

es-core/src/InputManager.cpp
=> JoystickGetAxisInitialState

es-core/src/components/GridTileComponent.cpp
fix when minSize is used without a label
fix for gridtile text visible & size elements
=> GridView : small fixes

locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po
=> pt_BR: review

locale/lang/es/LC_MESSAGES/emulationstation2.po
=> es_Translation_5.25-dev 2019/12/07 09:49

es-app/src/PlatformId.cpp
=> add: screenscraper jaguar

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiScraperStart.cpp, es-app/src/guis/GuiSystemsHide.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/ImageGridComponent.h
In es_systems.cfg file, use <group>name</group> under <system> element to move the system as a folder in a new system that will be created using "name". Theme management stay unchanged.
=> System Grouping : Support for group systems

es-core/src/components/GridTileComponent.cpp
=> GridView : Always show videos minSized to the size of the image

es-app/src/FileData.cpp
-> Random music is played instead.
=> Fix : Theme music are not played back when returning from a game

locale/lang/es/LC_MESSAGES/emulationstation2.po
=> 5.25-dev 2020/01/13 22:55

es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/GamesDBJSONScraperResources.cpp, es-core/src/HttpReq.cpp, es-core/src/components/OptionListComponent.h
+ Don't use streams anymore to write httpreq responses to file.
=> Scrapper : Fixed theGamesDB api url + ScreenScraper : add mixv2 + allow boxes as main image

es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-core/src/utils/StringUtil.cpp
- <video name="staticBackgroundVideo"> on system view for static video background effects
- Random playlist : change randomizer for better random ( and non working random on pi3 )
=> Add Support for "staticBackgroundVideo" on system view

es-app/src/views/SystemView.cpp, es-core/src/renderers/Renderer.cpp
=> GOA : Fix Flickering when scrolling + Set as "smallscreen" device like GPI case ( fullscreen menus )

locale/lang/es/LC_MESSAGES/emulationstation2.po
=> 5.25-dev 2020/01/24 17:12

es-app/src/MetaData.cpp, es-app/src/components/TextListComponent.h, es-app/src/scrapers/ThreadedScraper.cpp, es-core/src/components/ComponentList.cpp, es-core/src/components/ComponentList.h, es-core/src/components/DateTimeComponent.cpp, es-core/src/components/DateTimeEditComponent.cpp, es-core/src/components/ImageGridComponent.h, es-core/src/components/MenuComponent.cpp, es-core/src/components/MenuComponent.h, es-core/src/components/OptionListComponent.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h, es-core/src/components/VideoVlcComponent.cpp
- Fix : Metadata editor release date bad position
- Fix : GridView default game & folder image management
- Fix : ThreadedScraper not translated : added localisation support 
- Feat : Support for ComponentList & OptionListComponent Groups
=> Minor fixes

es-app/src/ApiSystem.cpp
=> update bt command

es-app/src/CollectionSystemManager.cpp, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-core/src/components/AsyncNotificationComponent.cpp, es-core/src/components/AsyncNotificationComponent.h, es-core/src/components/SliderComponent.cpp
It looks like locale has problems finding accents -> Process texts in the main UI thread.
=> Fix Download Notification Window : stop calculating fonts in a thread

es-app/src/guis/GuiWifi.cpp
then call "batocera-wifi scanlist" with a Busy Component
=> Wifi : if "batocera-wifi list" has an empty result,

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/EmulationStation.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/scrapers/ThreadedScraper.cpp, es-core/src/InputManager.cpp, es-core/src/InputManager.h, es-core/src/Log.cpp, es-core/src/ThemeData.cpp, es-core/src/VolumeControl.cpp
+ Scraper : Add Debug Logs 
+ Fix : Try to disable Volume Mute detection ( because entering the audio options sets volume to 0 on some machines )
+  Add Arcade auto collection ( groups every system having platform:arcade )
=> Logs : Add timestamp to log entries

es-app/src/guis/GuiNetPlay.cpp
rapidjson uses an assert making ES crash when a field is not found.
=> NetPlay : Secure json reading

locale/lang/es/LC_MESSAGES/emulationstation2.po
=> 5.25-dev 2020/02/08 09:51

es-app/src/ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiNetPlay.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/components/ButtonComponent.cpp, es-core/src/components/ComponentList.cpp, es-core/src/components/ComponentList.h, es-core/src/components/SliderComponent.cpp, es-core/src/resources/Font.h, locale/lang/fr/LC_MESSAGES/emulationstation2.po
Using groups...
+ Support menuGroup in themes 
+ Better looking for missing bios screen
=> Menus reorganisations 

es-app/src/SystemData.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/UIModeController.cpp, locale/lang/fr/LC_MESSAGES/emulationstation2.po
- Menus : Fixes for Kiosk & Kid & Bartop UI modes.
- Menus : Add groups management in theming options.
=> NetPlay : Add option check & run missing hash indexation at startup

es-app/src/guis/GuiMenu.cpp
=> display the index instead of the instance

es-core/src/InputConfig.cpp, es-core/src/InputConfig.h, es-core/src/InputManager.cpp
=> fix kodi inputs

locale/lang/es/LC_MESSAGES/emulationstation2.po
=> batocera-5.25-x86_64-20200216

es-app/src/ApiSystem.cpp, es-app/src/FileData.h, es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiNetPlay.cpp, es-app/src/guis/GuiSettings.h, es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/GamesDBJSONScraper.h, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/scrapers/ScreenScraper.h, es-app/src/scrapers/ThreadedScraper.cpp, es-app/src/scrapers/ThreadedScraper.h, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h, es-core/src/Settings.cpp, es-core/src/components/ButtonComponent.cpp, es-core/src/utils/FileSystemUtil.cpp
- System Grouping ( PORTS ) : Add an option to enable/disable Groups 
- System Grouping ( PORTS ) : Import folder metadata (If exists) from the source system gamelist.xml ( ie : <folder><path>.</path> ) in the virtual folder when grouping is active.
- Wifi : Hide SSID / Pass when wifi is disabled - Show them only when Wifi becomes active
- NetPlay : Add relay servers ( montreal, sao paulo ) + set default port if not existing
- Scraper : Secure requests (when free space is missing
- Http request : direct download file as .tmp files in the destination folder like regular browser do & rename them when finished instead of copying them from /tmp/ folder
-  Gamelists : Fix -> If the current gamelist.xml is corrupted, it can't be saved anymore
- UI : Fix buttons layout for small screens
=> Misc ( Wifi, Grouped systems, scraper... )

es-app/src/FileData.h, es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/Settings.cpp
per system option instead of a global option
=> Grouped System : Add an option to select systems to ungroup

es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiBezelInstallStart.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiRetroAchievements.cpp, es-app/src/guis/GuiThemeInstallStart.cpp, es-app/src/guis/GuiThemeInstallStart.h, es-core/CMakeLists.txt, es-core/src/components/MultiLineMenuEntry.h, es-core/src/components/OptionListComponent.h
=> Grouped Systems : Display the list of child systems to group in the sélection UI

es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/components/ImageGridComponent.h
+ Fix favorites not working in grouped systems
=> Grouped systems : Fix Navigation

es-app/src/guis/GuiMenu.cpp, locale/emulationstation2.pot, locale/lang/ar/LC_MESSAGES/emulationstation2.po, locale/lang/ca/LC_MESSAGES/emulationstation2.po, locale/lang/de/LC_MESSAGES/emulationstation2.po, locale/lang/el/LC_MESSAGES/emulationstation2.po, locale/lang/es/LC_MESSAGES/emulationstation2.po, locale/lang/eu_ES/LC_MESSAGES/emulationstation2.po, locale/lang/fr/LC_MESSAGES/emulationstation2.po, locale/lang/hu/LC_MESSAGES/emulationstation2.po, locale/lang/it/LC_MESSAGES/emulationstation2.po, locale/lang/jp_JP/LC_MESSAGES/emulationstation2.po, locale/lang/ko/LC_MESSAGES/emulationstation2.po, locale/lang/nb_NO/LC_MESSAGES/emulationstation2.po, locale/lang/nl/LC_MESSAGES/emulationstation2.po, locale/lang/nn_NO/LC_MESSAGES/emulationstation2.po, locale/lang/pl/LC_MESSAGES/emulationstation2.po, locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po, locale/lang/pt_PT/LC_MESSAGES/emulationstation2.po, locale/lang/ru_RU/LC_MESSAGES/emulationstation2.po, locale/lang/sv_SE/LC_MESSAGES/emulationstation2.po, locale/lang/tr/LC_MESSAGES/emulationstation2.po, locale/lang/zh_CN/LC_MESSAGES/emulationstation2.po, locale/lang/zh_TW/LC_MESSAGES/emulationstation2.po
=> add system info po

locale/lang/es/LC_MESSAGES/emulationstation2.po
=> batocera-5.25-x86_64-20200302

es-app/CMakeLists.txt, es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiBluetooth.cpp, es-app/src/guis/GuiBluetooth.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiWifi.cpp, es-core/src/InputManager.cpp, es-core/src/InputManager.h, es-core/src/SystemConf.cpp
=>  Bluetooth : new UI for paired bluetooth device removing 

es-app/CMakeLists.txt, es-app/src/Playlists.cpp, es-app/src/Playlists.h, es-app/src/views/SystemView.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h, es-core/src/components/VideoComponent.cpp
Used to rotate predefined images & videos ( ie : to play images animation )
Sample m3u file :
#EXTM3U
#EXT-X-TARGETDURATION:250
;#RESETONSHOW
;#RANDOM
neogeo.jpg
nes.jpg
ps2.jpg
psx.jpg
=> ImageComponent / VideoComponent : Support for m3u playlists

es-app/src/FileData.cpp
=> fix pad deinit/configure

es-app/src/guis/GuiMenu.cpp
=> dolphin-internal-resolution

locale/lang/ca/LC_MESSAGES/emulationstation2.po
=> New literals

es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiMenu.cpp, es-core/src/components/ImageGridComponent.h
```
<emulator name="emulatorname">
<feature name="PRESET" value="preset">
<choice name="MAX" value="max"/>
<choice name="MEDIUM" value="medium"/>
<choice name="MIN" value="min"/>
</feature>  
</emulator>
```
++ Fix emulator selection when no core available.
=> es_features : support for custom features.

es-core/src/InputConfig.h
=> up to 8 players

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/Win32ApiSystem.cpp, es-app/src/Win32ApiSystem.h, es-app/src/guis/GuiMenu.cpp
=> user and system disk usage

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/Gamelist.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiUpdate.cpp, es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-app/src/main.cpp, es-app/src/views/gamelist/DetailedContainer.cpp, es-app/src/views/gamelist/DetailedContainer.h, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/Settings.cpp, es-core/src/components/DateTimeComponent.cpp, es-core/src/components/ImageGridComponent.h, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoVlcComponent.cpp, es-core/src/platform.cpp, es-core/src/platform.h, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h, es-core/src/utils/TimeUtil.cpp
- GridView : add new <imagesource> value : marqueeortext 
- Fix : Exit sequence not firing script events
- Mute video screensaver audio  ( credits to pjft - retropie )
- Detailled views : fixes for new controls & simplified code
=> Misc & fixes

es-app/src/ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp, es-core/src/VolumeControl.cpp, es-core/src/VolumeControl.h
++ Fix Wrong exit codes on Linux
=>  Hide volume controls when no mixer available 

locale/lang/oc/LC_MESSAGES/emulationstation2.po
First commint to add Occitan language
=> [i18n] Add Occitan locale

es-app/src/guis/GuiMenu.cpp, locale/emulationstation2.pot, locale/lang/ar/LC_MESSAGES/emulationstation2.po, locale/lang/ca/LC_MESSAGES/emulationstation2.po, locale/lang/de/LC_MESSAGES/emulationstation2.po, locale/lang/el/LC_MESSAGES/emulationstation2.po, locale/lang/es/LC_MESSAGES/emulationstation2.po, locale/lang/es_MX/LC_MESSAGES/emulationstation2.po, locale/lang/eu_ES/LC_MESSAGES/emulationstation2.po, locale/lang/fr/LC_MESSAGES/emulationstation2.po, locale/lang/hu/LC_MESSAGES/emulationstation2.po, locale/lang/it/LC_MESSAGES/emulationstation2.po, locale/lang/jp_JP/LC_MESSAGES/emulationstation2.po, locale/lang/ko/LC_MESSAGES/emulationstation2.po, locale/lang/nb_NO/LC_MESSAGES/emulationstation2.po, locale/lang/nl/LC_MESSAGES/emulationstation2.po, locale/lang/nn_NO/LC_MESSAGES/emulationstation2.po, locale/lang/pl/LC_MESSAGES/emulationstation2.po, locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po, locale/lang/pt_PT/LC_MESSAGES/emulationstation2.po, locale/lang/ru_RU/LC_MESSAGES/emulationstation2.po, locale/lang/sv_SE/LC_MESSAGES/emulationstation2.po, locale/lang/tr/LC_MESSAGES/emulationstation2.po, locale/lang/uk_UA/LC_MESSAGES/emulationstation2.po, locale/lang/zh_CN/LC_MESSAGES/emulationstation2.po, locale/lang/zh_TW/LC_MESSAGES/emulationstation2.po
=> multimedia keys

es-app/src/scrapers/ScreenScraper.cpp
=> Fix NEOGEO_CD

locale/lang/oc_FR/LC_MESSAGES/emulationstation2.po
=> i18n Update for Occitan

es-core/src/components/ScrollableContainer.cpp
Discussed with @Darknior - better when large text boxes like RVGM
=> Slower scrolling for large text boxes

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/ContentInstaller.cpp, es-app/src/ContentInstaller.h, es-app/src/Win32ApiSystem.cpp, es-app/src/Win32ApiSystem.h, es-app/src/guis/GuiBatoceraStore.cpp, es-app/src/guis/GuiBezelInstallStart.cpp, es-app/src/guis/GuiThemeInstallStart.cpp, es-app/src/guis/GuiThemeInstallStart.h
Related to this PR by @lbrpdx -> https://github.com/batocera-linux/batocera.linux/pull/1995
=> Themes installer : rewritten UI on the same model than bezels & content installer

es-app/src/ApiSystem.h, es-app/src/FileSorts.cpp, es-app/src/FileSorts.h
+ Add sort by "Gametime" in gamelist sort options.
=>  Content downloader : Fix bad method to detect a package is installed 

es-app/src/guis/GuiMenu.cpp
=> view manual

es-app/src/guis/GuiBatoceraStore.cpp, es-app/src/views/ViewController.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/guis/GuiInfoPopup.cpp, es-core/src/guis/GuiInfoPopup.h
`+` Add support for multiple notification popups
=>  Fix Batocera Store Crash when updating package 

es-app/src/CollectionSystemManager.cpp, es-app/src/components/TextListComponent.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/scrapers/Scraper.cpp, es-core/CMakeLists.txt, es-core/src/ThemeData.cpp, es-core/src/components/ImageGridComponent.h, es-core/src/components/ScrollbarComponent.cpp, es-core/src/components/ScrollbarComponent.h
Using new theme properties on imagegrid & textlist components : scrollbarColor, scrollbarCorner and scrollbarSize
es-theme-carbon needs to be bumped.
=> TextListComponent/ImageGridComponent : Add themable scrollbar indicator

es-core/src/resources/Font.cpp
=> maximize font

es-app/src/guis/GuiMenu.cpp
=> Add "bezel stretch" option (for 4K and ultrawide)

es-app/src/guis/GuiMenu.cpp
And this is for master, to check with @fabricecaruso if he prefers to merge before or after his current works in progress.
=> Add "bezel strech" option (for 4K and ultrawide)

es-app/src/guis/GuiMenu.cpp
=> fix video mode option

es-app/src/ApiSystem.cpp
Only on master, ported the change required by https://github.com/batocera-linux/batocera.linux/pull/2196
=> Synced up "batocera-info" with latest CLI change

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiNetPlay.cpp, es-app/src/guis/GuiNetPlay.h, es-app/src/guis/GuiSettings.cpp, es-app/src/guis/GuiSettings.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/Settings.cpp, es-core/src/anim/ThemeAnimation.h, es-core/src/anim/ThemeStoryboard.cpp, es-core/src/components/ImageComponent.cpp
HideWindowFullReinit will allow to test gamesplash.xml on other boards.
=> Storyboards : initial support for path string ( image.path ) + Add HideWindowFullReinit to test gamesplash

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/CollectionSystemManager.cpp, es-app/src/FileSorts.cpp, es-app/src/SystemData.cpp, es-app/src/Win32ApiSystem.cpp, es-app/src/Win32ApiSystem.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/ThemeData.cpp, es-core/src/anim/StoryboardAnimator.cpp, es-core/src/anim/StoryboardAnimator.h, es-core/src/anim/ThemeStoryboard.cpp, es-core/src/anim/ThemeStoryboard.h, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoVlcComponent.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h
- Storyboards : Add support for <storyboard repeatAt="1000"> (repeatAt) attribute : This allows to repeat a complex animation at a given time.
- Storyboards : Add support for new properties : text.text, image.path
- TextComponent : Add support for text.autoscroll ( none/horizontal/vertical ) in themings, to activate auto scroll.
- VideoComponent : Add support for video.audio (true/false ) in theming, to enable/disable audio in videos.
- es_systems (linux) : check if custom file exists in userdata/system/configs/emulationstation/es_systems.cfg and load it instead
- es_systems (windows) : check if custom es_systems_custom.cfg file exists and load it instead.
- Manufacturer bar : fix potential crash.
- Shaders : Remove hardcoded list. load shaders list from filesystem instead.
- System sort …
=> Storyboards : Add support for <storyboard repeatAt="1000"> (repeatAt)… And many other things.

es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiBatoceraStore.cpp, es-app/src/guis/GuiBatoceraStore.h, es-app/src/services/HttpServerThread.cpp, es-core/CMakeLists.txt, es-core/src/components/ComponentList.cpp, es-core/src/components/ComponentList.h, es-core/src/components/ComponentTab.cpp, es-core/src/components/ComponentTab.h, es-core/src/components/DateTimeEditComponent.cpp, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h
+ Better management for /addGames REST API
=> Content Downloader : Tabbed UI when multiple repositories.

es-core/src/Settings.cpp
=> fix hide windows x86_64 type

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/FileData.cpp, es-app/src/guis/GuiBios.cpp, es-app/src/guis/GuiKeyMappingEditor.cpp, es-app/src/views/ViewController.cpp
+ use batocera-systems with --filter parameter for better performance
=> Fix .keys files paths to include original game extension

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/SystemData.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp
+ Fix : Crash when deleting a game from a group child ( ports/prboom )
=> Fix : Features are missing when another system is grouped into a "physical" group ( ports or windows... )

locale/lang/fr/LC_MESSAGES/emulationstation2.po
=> Update translation fr_FR

es-app/src/guis/GuiMenu.cpp, es-core/src/AudioManager.cpp, es-core/src/AudioManager.h, es-core/src/Window.cpp
- QuickMenu : Fix songname sometimes missing in "LISTENING NOW" item
- Latency Reduction : Add an option to disable it ( required to make a per-game override )
=> Small fixes

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiBatoceraStore.cpp, es-app/src/guis/GuiBatoceraStore.h
UI for https://github.com/batocera-linux/batocera.linux/pull/2489 with a new button "UPDATE ALL" separate from "REFRESH".
=> Don't upgrade all packages unless requested (refresh only)

es-app/src/CollectionSystemManager.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp
+ Faster reloadall using multitheading ( when refreshing or changing a theme )
=> Fix : games from hidden systems are still visible in collections

es-app/src/CollectionSystemManager.cpp, es-app/src/views/ViewController.cpp
+ Fix : Stupid crash since yesterday, when adding new collections...
=> Game from grouped systems ( like ports ) are missing from "all games" & custom collections

es-app/CMakeLists.txt, es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/FileData.cpp, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiCollectionSystemsOptions.h, es-app/src/guis/GuiGameOptions.cpp, es-app/src/guis/GuiGameOptions.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiGamelistOptions.h, es-app/src/guis/GuiMenu.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/DetailedContainer.cpp, es-app/src/views/gamelist/DetailedContainer.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/IGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/renderers/Renderer.cpp, es-core/src/resources/ResourceManager.h
=> UI : Split of Games Options (with Y) and Gamelist Options (with SELECT)

CMakeLists.txt, es-core/src/renderers/Renderer_GLES20.cpp, es-core/src/resources/TextureData.cpp
@fabricecaruso  can we try to get this back in and work together to debug the video playback (restart / resume) issue ?
It would be nice to have this for bato 30 release
=> Renderer optimization and compile in O3

es-app/src/MetaData.cpp, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/components/ScraperSearchComponent.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMetaDataEd.cpp, es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h, es-app/src/scrapers/ScreenScraper.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ComponentList.cpp, es-core/src/components/ComponentList.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageGridComponent.h
++ TheGamesDB : Add screenshot/titleshot/wheel/fanart management
-> This is really useful for systems like moonlight/windows/dosbox because Screenscraper has few games on those platforms.
=>  Manual scrap : Show results from both scrapers ( ScreenScraper + TheGamesDB ) 

es-app/src/components/ScraperSearchComponent.cpp, es-app/src/components/ScraperSearchComponent.h, es-app/src/scrapers/ArcadeDBJSONScraper.cpp, es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-core/src/HttpReq.cpp, es-core/src/components/BusyComponent.cpp, es-core/src/components/BusyComponent.h, es-core/src/components/ImageComponent.h, es-core/src/components/WebImageComponent.cpp, es-core/src/components/WebImageComponent.h, es-core/src/renderers/Renderer_GLES20.cpp, locale/lang/fr/LC_MESSAGES/emulationstation2.po
++ refactor ArcadeDB/TheGamesDB images to scrap selection according to settings
=> Manual scraper : Better thumbnail management 

es-app/src/views/gamelist/DetailedContainer.cpp, es-core/CMakeLists.txt, es-core/src/GuiComponent.cpp, es-core/src/InputManager.cpp, es-core/src/Window.cpp, es-core/src/renderers/GlExtensions.cpp, es-core/src/renderers/GlExtensions.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES20.cpp, es-core/src/renderers/Shader.cpp, es-core/src/renderers/Shader.h, es-core/src/resources/TextureData.cpp
=> OpenGL : Merge GLES20 & GL21 in a unique renderer using shaders ( now wordks on Linux Desktop and Windows, too )

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/FileFilterIndex.cpp, es-app/src/MetaData.cpp, es-app/src/RetroAchievements.cpp, es-app/src/SystemData.cpp, es-app/src/components/RatingComponent.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/views/ViewController.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/anim/ThemeStoryboard.cpp, es-core/src/math/Vector2f.cpp, es-core/src/math/Vector4f.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h, es-core/src/utils/ZipFile.cpp, external/id3v2lib/include/id3v2lib/frame.h, external/id3v2lib/src/frame.c, external/id3v2lib/src/id3v2lib.c
- Threaded loading for collections to speed up things
- Load features before loading collections ( cheevos related )
- Misc optimisations (toFloat, fromHexString, toInteger)
- Fix id3 crash with some mp3 files.
- RetroAchievements fix when username or password contains & or %
- Scraper : Reset imagecache for new scrapped medias
=> Misc improvements & optimizations

es-core/src/platform.cpp
=> p2p network

locale/lang/es/LC_MESSAGES/emulationstation2.po
accent marks, terminologies, nonsense capitalization, semantic
=> Full revision, spanish castillian, no error

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSaveState.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/components/SwitchComponent.cpp, locale/lang/fr/LC_MESSAGES/emulationstation2.po
This option allows to open the savestate manager with "south" before launching a game
=> AUTO SAVE/LOAD option : Add "SHOW SAVE SNAPSHOTS" in choices

locale/lang/es/LC_MESSAGES/emulationstation2.po
Another deep review. More intuitive texts according to what is shown on the UI. Correction of accents, spelling etc.
=> Locale ES_revision

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/SystemData.cpp, es-app/src/components/RatingComponent.cpp, es-app/src/components/RatingComponent.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiSettings.cpp, es-app/src/views/gamelist/DetailedContainer.cpp, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h
- "Reset Gamelist customizations" + extend the feature to reset the whole theme customizations
- Fix RatingComponent opacity management ( using multiplication of alpha channels )
- Fix wrong system sort order when loaded threading is disabled (or threadbycore <= 2 ) and when there are no collections
- Allow Threaded loading even if threadbycores count is 2
=> Some fixes 

resources/freeslot.svg
I think it is a more intuitive and logical icon, it does not discriminate language. Also, "NO DATA" I think is confusing, the option "start new game" only starts the game in fact. And the option "START AUTO SAVE" creates a new auto save slot.
=> icon type launch in "SAVE SNAPSHOTS" manager

es-app/src/ThreadedHasher.cpp, es-app/src/Win32ApiSystem.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/GameNameFormatter.cpp, es-core/src/InputManager.cpp, es-core/src/resources/Font.cpp
=> Fix country flags display using fontoverrides

es-app/CMakeLists.txt, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/components/CarouselComponent.cpp, es-app/src/components/CarouselComponent.h, es-app/src/guis/GuiFileBrowser.cpp, es-app/src/guis/GuiFileBrowser.h, es-app/src/guis/GuiGeneralScreensaverOptions.cpp, es-app/src/guis/GuiGeneralScreensaverOptions.h, es-app/src/guis/GuiMetaDataEd.cpp, es-app/src/guis/GuiMetaDataEd.h, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/gamelist/GameNameFormatter.cpp, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/ThemeData.cpp, es-core/src/components/ComponentGrid.cpp, es-core/src/components/ComponentGrid.h, es-core/src/components/MenuComponent.cpp, es-core/src/components/MenuComponent.h, es-core/src/utils/FileSystemUtil.cpp
Note : The theme needs to be bumped.
=> Add a file browser +  Add "transitionSpeed" & "minLogoOpacity" to Carousel Theming

es-core/src/renderers/Renderer.cpp
=> fix rotate on rpi

es-app/src/FileFilterIndex.cpp, es-app/src/SaveStateRepository.cpp, es-app/src/guis/GuiGameOptions.cpp, es-app/src/guis/GuiMenu.cpp
+  Text filter : Allow multiple filters, using ',' (comma) to separate them 
+  Scraper : Add NONE to IMAGE SOURCE
=> Game options : Simplify "Add to custom collection" option when multiple collections

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/SystemData.cpp, es-app/src/components/RatingComponent.cpp, es-app/src/main.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/CarouselGameListView.cpp, es-app/src/views/gamelist/DetailedContainer.cpp, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/components/HelpComponent.cpp, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h, es-core/src/resources/Font.cpp, es-core/src/resources/TextureData.cpp
Please bump es_theme_carbon again ( 6181edccd04af14e36582fe23218e987a3b06289 ).
-  Fix : crash when adding favorite with north long press 
-  Fix md_video not displayed & potential crashes with some themes
-  FontOverrides : trick for better looking 
-  Optimizations : Avoid too many reloads of svg files (logos/rating component)
=> Some more fixes & optimizations.

es-app/src/guis/GuiMenu.cpp, es-core/src/renderers/Renderer.h, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/renderers/Renderer_GLES20.cpp
=> gl infos for all boards

es-app/src/scrapers/ScreenScraper.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/CarouselGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/Window.cpp, es-core/src/utils/FileSystemUtil.cpp
=> Help : Update help to include long press + change order ( OK before BACK )

es-app/src/SystemData.cpp
=> fix es crash

es-app/src/CollectionSystemManager.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ImageGridComponent.h, es-core/src/resources/ResourceManager.cpp, external/nanosvg/nanosvg.h, external/nanosvg/nanosvgrast.h
- Gameslist Themes : Fix some extras can be loaded twice if they don't have storyboards.
-  Small optimizations
=>  Fix : 'Collections' system is missing from systemview & crashes when accessed navigating from gamelists

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/Win32ApiSystem.cpp, es-app/src/Win32ApiSystem.h, es-app/src/components/CarouselComponent.cpp, es-app/src/components/CarouselComponent.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiUpdate.cpp, es-app/src/guis/GuiUpdate.h, es-app/src/services/httplib.h, es-core/src/PowerSaver.cpp, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h, es-core/src/renderers/GlExtensions.cpp, es-core/src/renderers/GlExtensions.h, es-core/src/renderers/Renderer.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/renderers/Renderer_GLES20.cpp
=> OpenGLES2 renderer performance improvements

es-app/src/guis/GuiUpdate.cpp
=> fix back r

es-core/src/renderers/Renderer.cpp
=> fix mouse cursor

locale/lang/nl/LC_MESSAGES/emulationstation2.po
Dutch translations are 100% now, fixed a couple of typo's and changed some lowercase to uppercase
=> Completed the dutch translations

es-app/src/ApiSystem.cpp
=> Fix rounding errors while getting and setting brightness

locale/lang/es/LC_MESSAGES/emulationstation2.po
Same definition at line 866 to 872.
=> Remove locale es duplicate message definition.

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp
@fabricecaruso @nadenislamarre Option to change the color of the buttons and how the led works in GameForce.
=> gameforce: PowerLed and ButtonColorLed

locale/lang/ja_JP/LC_MESSAGES/emulationstation2.po
=> replace unusual full-width space

es-app/src/ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp
=> no reboot for audio

es-app/src/guis/GuiMenu.cpp
=> fix audio key name lists

es-app/src/main.cpp
=> remove done boot message

es-core/src/VolumeControl.cpp
=> fix pa crash

es-core/src/VolumeControl.cpp
=> fix pa crash 2

es-core/src/VolumeControl.cpp
=> fix pa thread

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h
=> reload external hooks

es-app/src/guis/GuiMenu.cpp
=> rotate option

es-app/src/guis/GuiMenu.cpp
=> menu for boot splash

es-app/src/services/HttpApi.cpp
=> fix api logo

resources/services/index.html, resources/services/main.css
=> play button

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp, locale/emulationstation2.pot, locale/lang/ar/LC_MESSAGES/emulationstation2.po, locale/lang/ca/LC_MESSAGES/emulationstation2.po, locale/lang/cy_GB/LC_MESSAGES/emulationstation2.po, locale/lang/de/LC_MESSAGES/emulationstation2.po, locale/lang/el/LC_MESSAGES/emulationstation2.po, locale/lang/es/LC_MESSAGES/emulationstation2.po, locale/lang/es_MX/LC_MESSAGES/emulationstation2.po, locale/lang/eu_ES/LC_MESSAGES/emulationstation2.po, locale/lang/fr/LC_MESSAGES/emulationstation2.po, locale/lang/hu/LC_MESSAGES/emulationstation2.po, locale/lang/it/LC_MESSAGES/emulationstation2.po, locale/lang/ja_JP/LC_MESSAGES/emulationstation2.po, locale/lang/ko/LC_MESSAGES/emulationstation2.po, locale/lang/nb_NO/LC_MESSAGES/emulationstation2.po, locale/lang/nl/LC_MESSAGES/emulationstation2.po, locale/lang/nn_NO/LC_MESSAGES/emulationstation2.po, locale/lang/oc_FR/LC_MESSAGES/emulationstation2.po, locale/lang/pl/LC_MESSAGES/emulationstation2.po, locale/lang/pt_BR/LC_MESSAGES/emulationstation2.po, locale/lang/pt_PT/LC_MESSAGES/emulationstation2.po, locale/lang/ru_RU/LC_MESSAGES/emulationstation2.po, locale/lang/sv_SE/LC_MESSAGES/emulationstation2.po, locale/lang/tr/LC_MESSAGES/emulationstation2.po, locale/lang/uk_UA/LC_MESSAGES/emulationstation2.po, locale/lang/zh_CN/LC_MESSAGES/emulationstation2.po, locale/lang/zh_TW/LC_MESSAGES/emulationstation2.po
=> audio profiles

es-app/src/PlatformId.cpp, es-app/src/PlatformId.h, es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/ScreenScraper.cpp
- Scrape Sonic Retro Engine
- Scrape TyrQuake as DOS games
=> Improve scraping

resources/services/index.html
=> Fix: sort games shown on the web services UI

es-app/src/guis/GuiMenu.cpp, es-core/src/components/ButtonComponent.cpp, es-core/src/guis/GuiInfoPopup.cpp, es-core/src/guis/GuiMsgBox.cpp
=> some tts fixes

locale/lang/ko/LC_MESSAGES/emulationstation2.po
clean up po file and fix wrong string
=> Update Korean translation

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/SystemData.cpp, es-app/src/guis/GuiGameOptions.cpp, es-app/src/guis/GuiImageViewer.cpp, es-app/src/guis/GuiImageViewer.h, es-app/src/guis/GuiMenu.cpp, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/DetailedContainer.cpp, es-core/src/Settings.cpp, es-core/src/TextToSpeech.cpp, es-core/src/TextToSpeech.h, es-core/src/components/ButtonComponent.h, es-core/src/components/VideoComponent.cpp, es-core/src/guis/GuiMsgBox.cpp
-  Game options : Add VIEW FULLSCREEN VIDEO && VIEW GAME MEDIAS items in the game menu.
- New developper option : Add "Preload medias option" ( off by default ) -> list files in medias (images/videos) folders, just to get OS build filesystem cache -> Less lags when navigating the UI but longest boot time. Usefull with slow HDDs.
- CONTROLLERS & BLUETOOTH SETTINGS : Windows does not have BLUETOOTH SETTINGS -> Adapt label for Windows
=>  TextToSpeech : Port for Windows + small fixes + play also description of games

README.md
Added mention of necessary step for Pi building and amended links from Retropie/emulationstation to batocera-linux/batocera-emulationstation.
=> Amended steps required to build.

CMakeLists.txt, es-app/CMakeLists.txt, es-app/src/FileData.cpp, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/HfsDBScraper.cpp, es-app/src/scrapers/HfsDBScraper.h, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h, es-app/src/services/httplib.h, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h, es-core/src/utils/TimeUtil.h, es-core/src/utils/ZipFile.cpp, es-core/src/utils/ZipFile.h
The account needs to be injected with -DHFS_DEV_LOGIN=XXXXX
@nadenislamarre : I'm currenly discussing with the HFSPlay Team to have different accounts for Batocera & Retrobat. I'll get back to you with the account information to inject as soon as it's ready.
=> New scrape engine : HFSDB

es-app/src/guis/GuiMenu.cpp
PRELOAD UI > PRELOAD UI ELEMENTS (Reduce overall menu lag at the cost of storage space)
PRELOAD MEDIAS FILESYSTEM (REDUCE UI LAGS OVER STARTUP TIME) > PRELOAD METADATA MEDIA (Reduce gamelist lag at the cost of storage space)
=> Update preload labels in dev options

es-app/src/guis/GuiMenu.cpp
As noted by @fabricecaruso in #1036.
Draft until confirmed that the strings still fit in correctly.
=> correct preload labels

locale/lang/pt_PT/LC_MESSAGES/emulationstation2.po
fixes issues caused by https://github.com/batocera-linux/batocera-emulationstation/pull/1041
=> pt_PT translation fix

es-app/src/guis/GuiMenu.cpp
New retroarch feature, related to https://github.com/batocera-linux/batocera.linux/pull/4998 on batocera.linux (pending PR to convert from draft)
=> add "auto frame delay" to latency settings

es-app/src/FileData.cpp, es-app/src/Gamelist.cpp, es-app/src/Gamelist.h
Exports game XML metadata - gamelist format
=> Add %GAMEINFOXML% variable for command lines

es-app/src/guis/GuiMenu.cpp
to see at a glance what the difference between regular shutdown vs. fast shutdown is
=> minor bgm label fixes + descriptive label to fast shutdown

es-app/src/guis/GuiMenu.cpp
add stuttering warning for "auto frame delay" setting in latency settings
@Hew-ux
=> add stuttering warning for "auto frame delay"

es-app/src/SystemData.cpp, es-app/src/scrapers/ArcadeDBJSONScraper.cpp, es-app/src/scrapers/ScreenScraper.cpp
+ don't parse artwork subfolder anymore when loading games
=> LCDGames : support in arcadeDBscraper

es-app/src/guis/GuiMenu.cpp
complements https://github.com/batocera-linux/batocera.linux/pull/5156
=> add challenge indicator option to retroachievements section

es-app/src/main.cpp
=> no-startup-game option

es-app/src/guis/GuiMenu.cpp
This setting is now a simple boolean value.
Should default to "on", but that aspect is not so important.
Complements https://github.com/batocera-linux/batocera.linux/pull/5242
=> change tattoo resize option to toggle

es-app/src/main.cpp, es-core/src/Settings.cpp, es-core/src/Splash.h, es-core/src/Window.cpp, es-core/src/Window.h
=> alternate splash image

es-app/src/guis/GuiMenu.cpp
=> pggettext on options

es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h
=> move some options to es_features

es-app/src/guis/GuiMenu.cpp, es-core/src/renderers/Renderer.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/renderers/Renderer_GLES20.cpp
=> fix convert color compilation

es-app/src/CustomFeatures.cpp
=> custom feature sorting

es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiScraperStart.cpp
and clarification on what options do.
=> Minor grammar/spelling corrections/consistency

es-app/src/views/gamelist/ISimpleGameListView.cpp
this will reduce the amount of support tickets by 99%
=> add (HOLD) to help label for functions activated by holding

es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h, es-core/src/components/VideoVlcComponent.cpp, es-core/src/components/VideoVlcComponent.h
pause/resume video instead of stop/reload
=> VideoVlcComponent : Pause video when a menu shows / resume playback when the menu closes

es-app/src/services/HttpServerThread.cpp
using "?confirm=switchscreen" parameter
=> Add switch screen confirmation on /quit http API

es-app/src/guis/GuiMenu.cpp
=> translate storage

es-app/src/guis/GuiMenu.cpp
=> max reslution

README.md
Confirmed by user Xargon# 3760 on the Discord.
=> add Arch/Manjaro compilation instructions to readme

es-app/CMakeLists.txt, es-app/src/CustomFeatures.cpp, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/SystemRandomPlaylist.cpp, es-app/src/SystemRandomPlaylist.h, es-app/src/Win32ApiSystem.cpp, es-app/src/services/HttpApi.cpp, es-app/src/services/HttpApi.h, es-app/src/services/HttpServerThread.cpp, es-app/src/views/SystemView.cpp, es-core/CMakeLists.txt, es-core/src/ImageIO.cpp, es-core/src/ImageIO.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h, es-core/src/components/WebImageComponent.cpp, es-core/src/components/WebImageComponent.h, es-core/src/playlists/AnimatedGifPlaylist.cpp, es-core/src/playlists/AnimatedGifPlaylist.h, es-core/src/playlists/M3uPlaylist.cpp, es-core/src/playlists/M3uPlaylist.h, es-core/src/resources/ResourceManager.cpp, es-core/src/resources/TextureData.cpp, es-core/src/resources/TextureData.h, resources/services/index.html, resources/services/main.css
- [ImageComponent] Support for animated Gifs & m3u (of images) playlists
- [Features] Fix Watch if autosave is provided as a shared feature
- [HttpApi] Add "/runningGame" API to get metadata from running game
=> Support for animated Gifs & m3u (of images) in ImageComponent + /runningGame HttpApi + Fix shared autosave feature

es-app/src/SystemData.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/views/UIModeController.cpp, es-app/src/views/UIModeController.h, es-core/src/Settings.cpp, es-core/src/Settings.h
=> Add new option "SHOW EMPTY SYSTEMS"

external/libcheevos/CMakeLists.txt, external/libcheevos/cheevos.cpp, external/libcheevos/rcheevos/src/rhash/cdreader.c
Works better with cue/bin files + adds supports for gdi/cdi files
=> Retroachivements : use defaut rcheevos cdreader for some formats

es-app/src/CollectionSystemManager.cpp, es-app/src/FileFilterIndex.cpp
Non-Themed Auto-Collections ( by Genre ) are not visible when unthemed collections are grouped into "Collections", when there is no custom collctions
=> Fix : Non-Themed Auto-Collections ( by Genre ) are not visible in some cases

es-core/src/guis/GuiInputConfig.cpp, es-core/src/guis/GuiInputConfig.h, es-core/src/utils/VectorEx.h
This replaces the previous PR - cleaner commit history and axis count check.
=> Trigger Input Filter v2

es-core/src/GunManager.cpp, es-core/src/InputManager.cpp, es-core/src/components/ControllerActivityComponent.cpp
+ Win32 simulation with WiimoteGun
=> Guns : ControllerActivity color when firing

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/FileFilterIndex.cpp, es-app/src/FileFilterIndex.h
https://github.com/batocera-linux/batocera-emulationstation/issues/1220
=> Feature: Add filter for games with missing media files / show only games with media files

es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h
Related to https://github.com/batocera-linux/batocera-emulationstation/issues/1101
=> Fix screensaver when all medias < random value are missing

es-core/src/GunManager.cpp, es-core/src/GunManager.h, es-core/src/Window.cpp
=> sinden gun borders

es-app/src/components/TextListComponent.h, es-app/src/views/SystemView.cpp, es-core/src/Window.cpp
+ Support for sinden.forceborders=1 for debugging purpose
=> Sinden border : support for sinden.bordersize=thin/big/medium in batocera.conf

resources/gungames.xml
=> specific gun for games

es-app/src/SystemData.cpp, es-core/CMakeLists.txt, es-core/src/Paths.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/anim/ThemeStoryboard.cpp, es-core/src/utils/HtmlColor.cpp, es-core/src/utils/HtmlColor.h, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h
+ Win32 : Fix kodi path detection 
+ Gamelists : never show flags in lists for imageviewer and ignore platforms
=> Themes : Support for Html color names ( aquamarine, cyan, darkblue, transparent, dimgray... )

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/FileData.cpp, es-app/src/guis/GuiImageViewer.cpp, es-app/src/main.cpp, es-core/CMakeLists.txt, es-core/src/ImageIO.cpp, es-core/src/components/ImageGridComponent.h, es-core/src/resources/TextureData.cpp, es-core/src/resources/TextureData.h, es-core/src/utils/StringListLock.cpp, es-core/src/utils/StringListLock.h
+  Mouse/Touch/Grid : Fix metadatas not updated when selection changed due to click event
+ GridView : better management & fix when image changes
+ ImageViewer/Library : Allow PDF & video previews + fix threading sync when extracting pdf & cbz previews
+ ImageCache : fix excluded paths were wrong
+ GuiImageViewer : Mouse/Touch support ( zooming & panning )
=> Mouse/Touch support / Grid View : Fix metadatas not updated when selection changed due to click event

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/SystemData.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiGeneralScreensaverOptions.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/CMakeLists.txt, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/Window.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/utils/MathExpr.cpp, es-core/src/utils/MathExpr.h
Applies on text & image components : `<image onclick="back" [...]`
Note : Please bump the theme, there are 2 working & useful samples in it.
- Gamelist View onclick actions : 
```
back
options
gameoptions
launch 
search
savestates
favorite
random
```
- System View onclick actions : 
```
netplay
navigationbar
search
open
random
prev
next
```
- use "none" to disable default click action for an element.
Applies to any element : ` <pos if="{system.name} == 'collections'" [...]` 
+ extend themes variable list. Variables are now :
global.architecture
global.help					( bool )
global.clock					( bool )
global.cheevos				( bool )
global.cheevos.username
global.netplay				( bool )
global.netplay.username
system.cheevos				( bool )
system.netplay				( bool )
system.savestates				( bool ) …
=> Introduce themable click actions + if condition for themes

es-app/src/components/TextListComponent.h, es-app/src/guis/GuiMenu.cpp, es-app/src/main.cpp, es-core/src/Log.cpp, es-core/src/Log.h, es-core/src/components/ComponentList.cpp, es-core/src/components/ComponentTab.cpp, es-core/src/renderers/Renderer.cpp
- Logs : it looks like multithreaded logging can crash ES...
- Fix mouse hit tests with some transformations
- Win32 only : SDL_WINDOW_BORDERLESS can cause black screen with some devices ( Ambernic Win600 )
=> Misc fixes

es-app/src/components/TextListComponent.h, es-core/src/Log.cpp
=> fix minor compilation error

es-app/src/guis/GuiRetroAchievementsSettings.cpp
* Add additional things that hardcore mode disables.
* Add description for verbose mode.
=> Update strings for retroachievement options

THEMES.md, es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/SystemData.cpp, es-app/src/guis/GuiHashStart.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/gamelist/GameNameFormatter.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/GunManager.h, es-core/src/components/HelpComponent.cpp, es-core/src/components/ImageGridComponent.h, es-core/src/components/MenuComponent.cpp, es-core/src/components/MultiLineMenuEntry.cpp, es-core/src/components/TextComponent.cpp, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/renderers/Renderer_GLES20.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/StringUtil.cpp
- GridView : fix game launch transition
- GridView : Fix CenterSelection
- Hashing : Grouped child systems are not visible for cheevos/netplay indexation
=> get/set Brightness : fixes detection for some laptops + other fixes

es-core/src/Window.cpp
=> guns options names

es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h
=> sinden options

resources/gungames.xml
=> update gun game

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h
=> reload sinden gun

resources/gungames.xml
=> update gun games

es-core/src/Window.cpp
=> adjust gun borders

es-app/src/guis/GuiMenu.cpp
a bit more descriptive as to what these new menus are for
=> rename to new gun settings menus

es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/Win32ApiSystem.cpp, es-core/src/GuiComponent.cpp, es-core/src/utils/TimeUtil.cpp, es-core/src/utils/TimeUtil.h
- Fix menus not showing sometimes
- Fix compilation with recent gcc versions
- Video screensaver : play next video if video ends ( when delay > video duration ) 
- Win32 : fix calls to executeScript that require outputs or progress
=> Somes fixes

THEMES.md
and fix up surrounding codeblocks
=> add ifarch documentation to readme

resources/gungames.xml
Removing model3 system since it's arcade.
=> Cleaning up gungames.xml

es-app/src/services/HttpServerThread.cpp
=> api quit menu

es-app/src/guis/GuiMenu.cpp
=> close window on suspend

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/FileData.cpp, es-app/src/NetworkThread.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-core/src/InputConfig.cpp, es-core/src/InputConfig.h, es-core/src/InputManager.cpp, es-core/src/InputManager.h, es-core/src/components/OptionListComponent.h, es-core/src/platform.cpp, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h
using SDL_JoystickPathForIndex when SDL2 version >= 2.24
=> [SDL/Win32] Better support for joystick path orders

es-app/src/ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp
=> allow 1% brightness

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h
=> version info for system api

es-app/CMakeLists.txt, es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiBluetoothForget.cpp, es-app/src/guis/GuiBluetoothForget.h, es-app/src/guis/GuiBluetoothPair.cpp, es-app/src/guis/GuiBluetoothPair.h, es-app/src/guis/GuiMenu.cpp, es-core/src/components/MenuComponent.cpp, es-core/src/components/MenuComponent.h, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h
batocera-bluetooth live_devices
batocera-bluetooth stop_live_devices 
batocera-bluetooth trust XXX
=> BlueTooth : rewrite for Batocera using scripts batocera-bluetooth live_devices

es-app/src/ApiSystem.cpp, es-app/src/CustomFeatures.cpp, es-app/src/SystemData.cpp, es-app/src/ThreadedBluetooth.cpp, es-app/src/ThreadedHasher.cpp, es-app/src/guis/GuiBluetoothForget.cpp, es-app/src/guis/GuiBluetoothForget.h, es-app/src/guis/GuiBluetoothPair.cpp, es-app/src/guis/GuiHashStart.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiNetPlaySettings.cpp, es-app/src/guis/GuiRetroAchievementsSettings.cpp, es-app/src/guis/GuiUpdate.cpp, es-core/src/components/ComponentList.cpp, es-core/src/components/ComponentList.h, es-core/src/components/MenuComponent.cpp, es-core/src/components/MenuComponent.h
NetPlay/Retroachivements : fix indexation for grouped systems
ApiSystem : Fix getVersion(extra) when batocera-version script does not exist
UI : better management for bluetooth icons
UI : group items on controller settings screen
UI : add groups to netplay/retroachivements screens + move username/pass at top of items
Custom es_systems/es_features : allow loading from /usr/ too.
=> Fixes & UI improvements

es-app/src/RetroAchievements.cpp, es-app/src/RetroAchievements.h, es-app/src/guis/GuiRetroAchievementsSettings.cpp, es-core/src/Window.cpp
Can be useful with some emulators
+ Theming : fix clock position changed after using a theme using clock.origin
=> Retroachivements : store token in global.retroachievements.token after successful login. 

resources/gungames.xml
+1 new game. Some precalibrations are missing for now. Will add them later (need more testing).
=> Adding precalibration to Wii games

es-app/src/ApiSystem.cpp
Installer should install to "/userdata/themes/" instead of "/userdata/system/configs/emulationstation/themes/"
=> [Linux] Theme installer : Fix wrong installation path.

resources/gungames.xml
=> I don't know how to type properly

es-core/src/platform.cpp
=> partial arch name for themes fixing

locale/lang/fr/LC_MESSAGES/emulationstation2.po
SOUTH, EAST, WEST, NORTH
LEFT and RIGHT SHOULDERS
D-PAD directions
Triggers
Stick pushes
=> Add joystick configuration translations in french

locale/lang/ar/LC_MESSAGES/emulationstation2.po
more translated entries/corrected past translation.
=> Update Arabic Translation

es-app/src/scrapers/ScreenScraper.cpp
=> Added wasm4 to screenscraper

locale/lang/ar/LC_MESSAGES/emulationstation2.po
Finished translating.
https://photos.app.goo.gl/HqNLE8HAw1Q1CmPd8
=> Update Arabic (100%)

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiBatoceraStore.cpp, es-app/src/guis/GuiBatoceraStore.h
Applies only if one the <package> element has a <preview_url> child element.
=> [Store] Add an optionnal support for preview images 

es-app/src/services/HttpServerThread.cpp
most of web framework, handling differed media types too hard.
we hope to unify it.
=> [Suggestion] runningGame API always return a JSON

es-app/src/PlatformId.cpp
=> Fix Atari XE scraping (#1405)

resources/gungames.xml
Virtua Cop and Death Crimson OX (different names depending on the region ROM)
=> fixing two gun games titles

es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiMenu.cpp
Apply for when #if BATOCERA only
=> [Updates] Fix "butterfly" which has become the new "beta" name even for Win32 or other distributions

es-app/src/Genres.cpp, es-app/src/Genres.h, resources/genres.xml
can show (tentative) Japanese genres.
(P.S.)
I'm not well informed international game genres.
maybe need fix these translations.
=> [Add] Japanese genres

es-core/src/AudioManager.cpp
Update to make scaling volume curve more gradual.
=> Update to logarithmic music volume formula

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-app/src/guis/GuiMenu.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ControllerActivityComponent.cpp, es-core/src/components/ControllerActivityComponent.h
what do you suggest for : //mPlanemodeEnabled = Settings::ShowNetworkIndicator() && ApiSystem::getInstance()->isPlanemode(); ?
not sure about icon names. i've added one in the theme.
=> plane mode

es-core/src/utils/Platform.cpp
When not waiting for child scripts, reap zombies and avoid calling exit handlers
- Call fork() twice and wait for first child, to prevent zombie processes.
- Call _exit() instead of exit() from the forked subprocesses, to prevent flushing STDIO buffers and skip calling exit handlers.
- Use execl() instead of system() to avoid keeping the intermediate forked grandchild around longer than necessary.
=> Fix hang when running ES scripts asynchronously

resources/wheelgames.xml
Trimming down to only games with wheel support (dial, paddle, analog stick input that have axis-range).
=> Initial wheel games database (WIP, VERY INCOMPLETE)

es-core/src/LocaleES.cpp
=> fix win32 locale processing

es-app/src/ApiSystem.cpp, es-app/src/ApiSystem.h, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h
Fixed an issue where the progress bar did not appear when downloading theme over 2G
=> Fixed an issue where the progress bar did not appear when downloading theme over 2G

es-app/src/KeyboardMapping.cpp, es-app/src/Win32ApiSystem.cpp, es-app/src/guis/GuiImageViewer.cpp, es-core/src/ThemeData.cpp, es-core/src/resources/Font.cpp
GuiImageViewer.cpp:  Fix warning
KeyboardMapping.cpp: Fix crash rare case
Win32ApiSystem.cpp: Fix wrong compare
Font.cpp: Fix crash no font
ThemeData.cpp: Fix wrong type cast, missing win32 unicode process
=> Fix small problem

es-core/src/components/ComponentGrid.cpp
=> fix assert error

es-core/src/GunManager.cpp, es-core/src/GunManager.h, es-core/src/components/ComponentGrid.cpp
Fix warning when compiling on Linux.
=> Fix warning

es-app/src/FileFilterIndex.cpp, es-app/src/FileFilterIndex.h, es-app/src/Gamelist.cpp, es-app/src/Gamelist.h, es-app/src/guis/GuiMenu.cpp
+ [Filters] Split HAS MEDIAS filter in two different filters : HAVING MEDIAS / MISSING MEDIAS, and propose every possible media
+ Developper tools : Add RESET GAMELISTS USAGE DATA tool
=> [Filters] Split HAS MEDIAS filter in two different filters : HAVING MEDIAS / MISSING MEDIAS, and propose every possible media

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-core/src/ImageIO.cpp, es-core/src/ImageIO.h, es-core/src/Window.cpp, es-core/src/components/AnimatedImageComponent.cpp, es-core/src/components/BusyComponent.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h, es-core/src/components/WebImageComponent.cpp, es-core/src/components/WebImageComponent.h, es-core/src/resources/TextureData.cpp, es-core/src/resources/TextureData.h, es-core/src/resources/TextureDataManager.cpp, es-core/src/resources/TextureResource.cpp, es-core/src/resources/TextureResource.h
=> Fix VRAM issues since last commit

es-app/src/FileData.cpp, es-app/src/SystemData.cpp, es-app/src/guis/GuiNetPlay.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/CarouselGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/BindingManager.cpp, es-core/src/ImageIO.cpp, es-core/src/ImageIO.h, es-core/src/components/ControllerActivityComponent.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/resources/Font.cpp, es-core/src/resources/TextureData.cpp, es-core/src/resources/TextureData.h, es-core/src/resources/TextureDataManager.cpp, es-core/src/resources/TextureDataManager.h, es-core/src/resources/TextureResource.cpp, es-core/src/resources/TextureResource.h, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h, es-core/src/utils/MathExpr.cpp, resources/shaders/border.glsl
+ Fix some expressions not working
+ Add {collection:XXX} dynamic variables ( of type system ) for collection systems
=> [TextureDataManager] Simplify class & Fix (again) SVG scaling

es-core/src/renderers/Renderer.cpp, es-core/src/renderers/Renderer.h, es-core/src/renderers/Renderer_GLES20.cpp, es-core/src/renderers/Shader.cpp, es-core/src/renderers/Shader.h
Use same names as retroarch glsl shaders
=> [Shaders] Add support for FrameCount and FrameDirection to allow animated shaders

es-core/src/components/ImageComponent.cpp
In case of a theme has made a size or minSize bigger than 1
=> [ImageComponent] Limit maxSize parameter to screen resolution

es-app/src/RetroAchievements.cpp, es-app/src/ThreadedHasher.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ImageComponent.cpp
+ [Theming/ImageComponent] Add support for <autoFade> bool element ( to enable/disable image fading when it's loaded )
=> [RetroAchievements] Manage HTTP errors on doRequest.php ( as they recently blocked us... )

es-app/src/RetroAchievements.cpp, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h
doRequest.php filters useragents. we are stuck with a 503 error with a non empty useragent
=> [RetroAchievements] Temporarily ( or not ) use empty UserAgent with some apis

resources/wheelgames.xml
WIP
Focusing on PS2 (+ adding few more games to the database)
=> Optimizing wheel games (part 1)

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/scrapers/ScreenScraper.h, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/CarouselGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/components/IList.h, es-core/src/utils/Uri.h
+ Also add crc argument to ScreenScraper requests when it's already known.
=> [Collections] Fix occasional crashes when removing games from collections + [ScreenScraper] Add romtaille to requests with md5

resources/gamesdb.xml
These 3 files will be removed once every launcher is adapted.
=> [GamesDB] Initial version for gamesdb.xml file, which is a merge of wheelgames.xml, gungames.xml and metadatagames.xml

resources/gamesdb.xml, resources/gamesdb.xsd
Every new change to gamesdb.xml must be validated with the schema
=> [GamesDB] Add gamesdb.xsd as a description for gamesdb.xml

es-app/src/SystemData.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/SystemViewControlWrapper.h, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/components/CarouselComponent.cpp, es-core/src/components/CarouselComponent.h, es-core/src/components/GridTileComponent.cpp, es-core/src/components/IList.h, es-core/src/components/ImageGridComponent.h, es-core/src/components/RectangleComponent.cpp, es-core/src/components/RectangleComponent.h
=> [SystemView] Add ability to use imagegrid or textlist to replace carousel in the systemview

es-app/src/EmulationStation.h, es-app/src/guis/GuiBios.cpp, es-app/src/guis/GuiBios.h, es-app/src/main.cpp, es-core/src/HttpReq.cpp, es-core/src/HttpReq.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES20.cpp
[ScreenScraper] Change default softname for batocera & retrobat
[OpenGL/Win32] remove callt to glFinish() as it makes some IntelHD GPUs
[Bios] Add tabbed UI. Default tab displays only active systems
=> [ScreenScraper/Http Requests] Store cookies to handle session cookies + [OpenGL/Win32] remove callt to glFinish() as it makes some IntelHD GPUs

resources/gamesdb.xml
Fixes order of tokyo xtreme racing 1 and 2 games.
=> fix gamesdb order

es-core/src/Scripting.cpp, es-core/src/utils/Platform.cpp, es-core/src/utils/Platform.h
=> Don't clobber ES logs when running game-end scripts

resources/gamesdb.xml, resources/gungames.xml
User needs to shake to progress at a certain point, and to push back close enemies. Without this, user can't finish the game.
=> add shake for hotdoverkill (wii)

resources/gamesdb.xml
Because all the values are at the bottom of the file for some reason?... therefore Batocera is not loading the values for wheel
=> Removing duplicate/fixing arcade optimization

resources/gamesdb.xml
I don't know why I forgot to add it. It works with steering wheel. Not the first one tho.
=> add burnout 2 (gc)

locale/lang/fr/LC_MESSAGES/emulationstation2.po
add translations
standardisation of keywords
mistake correction
=> enhance french locale

es-app/src/scrapers/ScreenScraper.cpp
https://www.screenscraper.fr/systemeinfos.php?plateforme=269
=> [Screenscraper] Update Teknoparrot platform ID

es-app/src/LangParser.cpp
See the discussion here: 
https://github.com/batocera-linux/batocera-emulationstation/issues/1686
=> Region detection improvements

es-app/src/guis/GuiMenu.cpp
- be clearer on the condition
- also for switchoff, write config to 1 only when toggled on (true).
=> fix switch on / off.

locale/lang/fr/LC_MESSAGES/emulationstation2.po
This reverts commit 5c2783971ac101f65f6b3deaa8ec6592bd9e8393, reversing changes made to 3dcc978c9c865985e4b365ab14e162e2216bda5f.
=> Revert "Merge pull request #1753 from 1e1/locale_fr"

es-core/src/utils/Platform.cpp
This reverts commit 23acaf003367c12eb85f63f39b9e8127fdb3fbc2, reversing changes made to ee8cbddd41930eed8fbe429f3ba0783a0f059dcc.
=> Revert "Merge pull request #1744 from dmanlfc/battery-fix"

locale/lang/fr/LC_MESSAGES/emulationstation2.po, resources/gamesdb.xml
Arcade platform takes priority over other platforms, gun icon will only be displayed if the game appears in arcade system in gamesdb
=> Move teknoparrot inside arcade system

es-core/src/utils/Platform.cpp
=> linux & win compatible

resources/gamesdb.xml
Uppercase is necessary, else ES does not find the games
=> Fix teknoparrot titles and add gun + wheel games

es-app/src/FileData.cpp, es-app/src/views/ViewController.cpp, es-core/src/Splash.cpp, es-core/src/Splash.h, es-core/src/Window.cpp, es-core/src/Window.h
exemple in gamesplash.xml : 
<image name="background">
<path>exists({game:fanart})?{game:fanart}:{game:image}</path>
</image>
=> [GameSplash] Allow dynamic game/system variables (bindings) with gamesplash.xml

es-app/src/guis/GuiMenu.cpp, es-core/src/components/SliderComponent.cpp, es-core/src/components/SliderComponent.h
Fixed :
- no impact on normal slider
- knob disappears when in AUTO
=> Add sliderauto component

resources/gamesdb.xml
This is ground foundation for future trackball support out of the box.
Note for the future: adjust trackball's sensitivity per game.
=> Initial game database for trackball devices

resources/gamesdb.xml
**WIP -ATARI 2600, ATARI 8-BIT & ARCADES**
These games have a very unique control board:
Discs of Tron (Tron)
Forgotten Worlds
Kozmik Kroozr kroozr
Zwackery zwackery
They had a push/pull spinner and flightstick with 2 buttons. Maybe in the future this will be added to the list.
Self-note about spinners: pulse/per rotation is important to standardize. Same for trackballs. Mandatory documentation: https://wiki.arcadecontrols.com/index.php/Spinner_Turn_Count
Note for later: some steering wheel games were in fact a spinner with a wheel on it. All those 360 degrees range games (infinite rotation).
=> Add more trackball games and initial spinner games db

es-app/src/guis/GuiMenu.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h
Allow to fast jump to previous/next game letter with L2/R2.
=> gamelist: add quick jump letter option

locale/lang/hu/LC_MESSAGES/emulationstation2.po
Hungarian translation: Corrected typos and wording in emulationstation2.po
=> Hungarian translation corrected

es-app/src/guis/GuiGameOptions.cpp, es-app/src/guis/GuiNetPlaySettings.cpp, es-app/src/views/ViewController.cpp, es-core/src/Settings.cpp, es-core/src/Settings.h
Added an option to proceed with the existing sequence as discussed.
https://github.com/batocera-linux/batocera-emulationstation/pull/1799#issuecomment-2444008724
=> Added SHOW NETPLAY OPTIONS WHEN LAUNCHING GAME option.

es-app/src/main.cpp
Batocera needs this to support fixes for #13111
=> Generate or refresh cheevos token at startup

es-app/src/main.cpp
Addresses the feedback in https://github.com/batocera-linux/batocera-emulationstation/pull/1846#issuecomment-2562870242
=> Move cheevos token refresh to a thread

resources/gamesdb.xml
WIP, totally uncomplete
MSX system: must use OpenMSX emulator.
NES system: must use Arkanoid pad/controller for Arkanoid 1 and 2.
Added and fixed few light gun games too.
=> Bit more spinner/trackball games

resources/gamesdb.xml
correct name is `ghostsev` which is already there
add all missing revisions of gun/wheel games
=> more lindbergh games

es-core/src/renderers/Renderer_GLES20.cpp
=> [Font artefacts] Fix for GLES20Renderer::createTexture 

es-app/src/guis/GuiNetPlay.cpp
Resolved the following warnings
```
es-app/src/guis/GuiNetPlay.cpp:753:1: warning: no return statement in function returning non-void [-Wreturn-type]
```
=> silence warnings

es-core/src/BindingManager.cpp, es-core/src/Settings.cpp, es-core/src/Settings.h, es-core/src/ThemeData.cpp
exemple : ${settings.ScrollLoadMedias}
=> [Theming] Expose settings to Themes & bindings using {settings.XXXX} (dynamic) and ${settings.XXXX} (const) variables

es-core/src/HttpReq.cpp, es-core/src/resources/TextureData.cpp
+ [Svg] Fix potential memory leak
=> [Win32] Fix curl optionCURLOPT_REDIR_PROTOCOLS option call based on current dll version.

resources/gamesdb.xml
add vf5 franchise names
typo in two after burner climax types
Based on https://github.com/lindbergh-loader/lindbergh-loader/blob/master/docs/guide.md
=> update lindbergh list

resources/gamesdb.xml
`2` is for menu/pause. You can exit current game to change mode/character/etc
=> [lightgun] add pause menu to ghost squad (wii)

es-core/src/ThemeData.cpp
ex :  <delay>${subset.video_gamelist_delay}</delay>
=> [Theming] Allow access to subset values with variables

es-app/src/SystemData.cpp
https://github.com/batocera-linux/batocera-emulationstation/issues/1795
=> #1795 The most played game data should show the most played based in time spent

es-app/src/guis/GuiRetroAchievementsSettings.cpp
This is used by dolphin and pcsx2 for example, it can be used to unlock unofficial achievements
=> [CHEEVOS MENU] Add unofficial achievements switch

es-app/src/views/ViewController.cpp, es-core/src/resources/TextureData.cpp, es-core/src/utils/ZipFile.cpp, es-core/src/utils/ZipFile.h
Would you be OK with defaulting to "fast" slide transition for launching games? It makes the whole experience feel snappier to me.
Please chime in if you disagree @fabricecaruso @dmanlfc @nadenislamarre @Tartifless
=> Switch to "fast" default transition

resources/gamesdb.xml
Because some people still live in prehistoric times
=> add older romset arkanoid name

es-core/src/utils/Platform.cpp
Skips over displaying ipv6 local link
=> ignore-ipv6-local-link

resources/gamesdb.xml
Actionmax + view new Hypseus Singe games
=> add some hypseus name ID

es-app/src/CustomFeatures.cpp
With this change, es_features can now manage multiple systems separated with coma for a features set:
This was already the case for core, where you could put the same set of features for multiple cores.
Example:
```
<system name="megadrive, genesis">
<feature name="ASPECT RATIO" group="GENERAL SETTINGS" value="jgen_genesis_ratio" order="25">
<choice name="NTSC" value="Ntsc"/>
<choice name="PAL" value="Pal"/>
<choice name="SQUARE PIXELS" value="SquarePixels"/>
<choice name="STRETCHED" value="Stretched"/>
</feature>
<feature submenu="VIDEO" name="NO SPRITE LIMIT" group="ADVANCED SETTINGS" value="jgen_spritelimit" description="Remove the sprites per line limit which can reduce or remove sprite flicker in some games." preset="switchauto" order="160"/>
<feature submenu="VISUAL RENDERING" …
```
=> Allow es_features to have multiple systems separated with coma
